# Generated by Django 4.2.2 on 2025-11-14 12:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0008_alter_departmentdownload_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the research",
                        max_length=300,
                        verbose_name="Research Title",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Detailed description of the research",
                        verbose_name="Research Description",
                    ),
                ),
                (
                    "abstract",
                    models.TextField(
                        blank=True,
                        help_text="Brief abstract of the research",
                        verbose_name="Abstract",
                    ),
                ),
                (
                    "research_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Research"),
                            ("applied", "Applied Research"),
                            ("experimental", "Experimental"),
                            ("theoretical", "Theoretical"),
                            ("review", "Review/Survey"),
                            ("case_study", "Case Study"),
                            ("other", "Other"),
                        ],
                        default="applied",
                        max_length=20,
                        verbose_name="Research Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("published", "Published"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="proposed",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "principal_investigator",
                    models.CharField(
                        help_text="Name of the principal investigator",
                        max_length=200,
                        verbose_name="Principal Investigator",
                    ),
                ),
                (
                    "pi_email",
                    models.EmailField(
                        help_text="Email of the principal investigator",
                        max_length=254,
                        verbose_name="PI Email",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "funding_agency",
                    models.CharField(
                        blank=True,
                        help_text="Name of the funding agency",
                        max_length=200,
                        verbose_name="Funding Agency",
                    ),
                ),
                (
                    "funding_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total funding amount",
                        max_digits=12,
                        null=True,
                        verbose_name="Funding Amount",
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Research keywords (comma separated)",
                        verbose_name="Keywords",
                    ),
                ),
                (
                    "methodology",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Research methodology",
                        verbose_name="Methodology",
                    ),
                ),
                (
                    "expected_outcomes",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Expected research outcomes",
                        verbose_name="Expected Outcomes",
                    ),
                ),
                (
                    "publications_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to publications/papers",
                        verbose_name="Publications URL",
                    ),
                ),
                (
                    "project_url",
                    models.URLField(
                        blank=True,
                        help_text="Project website URL",
                        verbose_name="Project URL",
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        help_text="GitHub repository URL",
                        verbose_name="GitHub URL",
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload research report PDF",
                        upload_to="research/reports/",
                        verbose_name="Research Report",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Research thumbnail image",
                        upload_to="research/thumbnails/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as featured research",
                        verbose_name="Featured Research",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Make research visible to public",
                        verbose_name="Published",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Views Count"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary department (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="department.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Research",
                "verbose_name_plural": "Research",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name",
                        max_length=100,
                        unique=True,
                        verbose_name="Category Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL slug for the category",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Category description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#10B981",
                        help_text="Hex color code for the category",
                        max_length=7,
                        verbose_name="Color",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Category",
                "verbose_name_plural": "Research Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResearchPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the publication",
                        max_length=300,
                        verbose_name="Publication Title",
                    ),
                ),
                (
                    "journal_conference",
                    models.CharField(
                        help_text="Name of journal or conference",
                        max_length=200,
                        verbose_name="Journal/Conference",
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Publication Date"
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier",
                        max_length=100,
                        verbose_name="DOI",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the publication",
                        verbose_name="Publication URL",
                    ),
                ),
                (
                    "citation_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of citations",
                        verbose_name="Citation Count",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="research.research",
                        verbose_name="Research",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Publication",
                "verbose_name_plural": "Research Publications",
                "ordering": ["-publication_date"],
            },
        ),
        migrations.CreateModel(
            name="ResearchParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full name of the participant",
                        max_length=200,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "participant_type",
                    models.CharField(
                        choices=[
                            ("faculty", "Faculty"),
                            ("staff", "Staff"),
                            ("student", "Student"),
                            ("external", "External Collaborator"),
                        ],
                        help_text="Type of participant",
                        max_length=20,
                        verbose_name="Participant Type",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Participant's email address",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Participant's phone number",
                        max_length=20,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True,
                        help_text="Job title/designation",
                        max_length=200,
                        verbose_name="Designation",
                    ),
                ),
                (
                    "roll_number",
                    models.CharField(
                        blank=True,
                        help_text="Student's roll number (if applicable)",
                        max_length=50,
                        verbose_name="Roll Number",
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        help_text="Organization name (for external collaborators)",
                        max_length=200,
                        verbose_name="Organization",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        default="Researcher",
                        help_text="Role in the research project",
                        max_length=100,
                        verbose_name="Role",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        help_text="LinkedIn profile URL",
                        verbose_name="LinkedIn URL",
                    ),
                ),
                (
                    "orcid_id",
                    models.CharField(
                        blank=True,
                        help_text="ORCID identifier",
                        max_length=50,
                        verbose_name="ORCID ID",
                    ),
                ),
                (
                    "is_corresponding_author",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the corresponding author?",
                        verbose_name="Corresponding Author",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Participant's department",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="department.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="research.research",
                        verbose_name="Research",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Participant",
                "verbose_name_plural": "Research Participants",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ResearchCategoryAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_assignments",
                        to="research.researchcategory",
                    ),
                ),
                (
                    "research",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_assignments",
                        to="research.research",
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Category Assignment",
                "verbose_name_plural": "Research Category Assignments",
                "unique_together": {("research", "category")},
            },
        ),
    ]
