# Generated by Django 4.2.2 on 2025-11-14 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0012_delete_staffmember"),
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="research",
            name="academic_program",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to a specific academic program (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="research_items",
                to="department.academicprogram",
                verbose_name="Academic Program",
            ),
        ),
    ]
