# Generated by Django 4.2.2 on 2025-11-23 07:55

from django.db import migrations, models
from django.utils.text import slugify


def populate_research_slugs(apps, schema_editor):
    Research = apps.get_model("research", "Research")

    for research in Research.objects.all():
        base_slug = slugify(getattr(research, "slug", None) or research.title) or "research"
        candidate = base_slug
        counter = 2

        while (
            Research.objects.filter(slug=candidate)
            .exclude(pk=research.pk)
            .exists()
        ):
            candidate = f"{base_slug}-{counter}"
            counter += 1

        if research.slug != candidate:
            research.slug = candidate
            research.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_research_academic_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for the research', max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.RunPython(populate_research_slugs, migrations.RunPython.noop),
    ]
