# Generated by Django 4.2.2 on 2025-07-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='is_system_managed',
        ),
        migrations.AddField(
            model_name='userrole',
            name='is_cms_role',
            field=models.BooleanField(default=False, help_text='Is this role for CMS Users', verbose_name='Is CMS Role'),
        ),
    ]
