# Generated by Django 4.2.2 on 2025-11-20 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_merge_20251119_1437'),
        ('user', '0002_user_classification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sections', to='website.campussection', verbose_name='campus section'),
        ),
        migrations.AddField(
            model_name='user',
            name='campus_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_units', to='website.campusunit', verbose_name='campus unit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMIS-STAFF', 'EMIS Staff'), ('ADMIN', 'Admin'), ('DEPARTMENT-ADMIN', 'Department Admin'), ('CLUB', 'Student Club'), ('UNION', 'Union'), ('CAMPUS-UNIT', 'Campus Unit'), ('CAMPUS-SECTION', 'Campus Section')], default='EMIS-STAFF', max_length=32, verbose_name='role'),
        ),
    ]
