# Generated by Django 4.2.2 on 2025-11-19 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "requester_name",
                    models.CharField(max_length=255, verbose_name="requester name"),
                ),
                (
                    "requester_email",
                    models.EmailField(max_length=254, verbose_name="requester email"),
                ),
                (
                    "requester_phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="requester phone"
                    ),
                ),
                (
                    "requester_student_id",
                    models.CharField(
                        blank=True,
                        help_text="Optional student ID if requester is a student",
                        max_length=50,
                        verbose_name="student ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="subject")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "preferred_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="preferred date"
                    ),
                ),
                (
                    "preferred_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="preferred time"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "response_message",
                    models.TextField(blank=True, verbose_name="response message"),
                ),
                (
                    "responded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="responded at"
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="scheduled date"
                    ),
                ),
                (
                    "scheduled_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="scheduled time"
                    ),
                ),
                (
                    "meeting_location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="meeting location"
                    ),
                ),
                (
                    "meeting_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about the meeting",
                        verbose_name="meeting notes",
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="email sent"),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="email sent at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_admin",
                    models.ForeignKey(
                        help_text="Admin to meet with (Campus Chief, Assistant, HOD, DHOD)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meeting_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responded_enquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "meeting enquiry",
                "verbose_name_plural": "meeting enquiries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["requested_admin", "status"],
                        name="enquiry_mee_request_6c75c5_idx",
                    ),
                    models.Index(
                        fields=["requester_email"],
                        name="enquiry_mee_request_2daed6_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="enquiry_mee_status_34a1c2_idx",
                    ),
                ],
            },
        ),
    ]
