# Generated by Django 4.2.2 on 2025-07-15 03:54

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Department of Electronics and Computer Engineering', 'DOECE'), ('Department of Civil Engineering', 'DOCE'), ('Department of Industrial Engineering', 'DOIE'), ('Department of AutoMobile and Mechanical Engineering', 'DOAME'), ('Department of Architecture', 'DOARCH'), ('Department of Applied Science', 'DOAS'), ('Administration', 'Admninistration'), ('Financial Administration Section', 'Financial Administration Section'), ('Planning Section', 'Planning Section'), ('General Administration Section', 'General Administration Section'), ('Personnel Administration Section', 'Personnel Administration Section'), ('Academic Administration and Examination Section', 'Academic Administration and Examination Section'), ('Store Section', 'Store Section'), ('Facilities Section', 'Facilities Section'), ('Library Section', 'Library Section'), ('Education Management Information System Unit', 'Education Management Information System(EMIS) Unit'), ('Research and Development Unit', 'Research and Development Unit'), ('Material Testing Laboratory', 'Material Testing Laboratory'), ('Examination and Academic Administration', 'Examination and Academic Administration'), ('Finance Administration Unit', 'Finance Administration Unit'), ('Main Store Unit', 'Main Store Unit'), ('Consultancy Services', 'Consultancy Services')], default='DOECE', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('introduction', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('routine', models.ImageField(blank=True, null=True, upload_to='media/routine/')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='media/profile/')),
                ('is_academic', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_academic'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(choices=[('CHIEF', 'Campus Chief'), ('ASSIST_CAMPUS_CHIEF_ADMIN', 'Assistant Campus Chief (Administration)'), ('ASSIST_CAMPUS_CHIEF_ACADEMIC', 'Assistant Campus Chief (Academic)'), ('ASSIST_CAMPUS_CHIEF_PLANNING', 'Assistant Campus Chief (Planning and Resource Management)'), ('ASSIST_CAMPUS_CHIEF', 'Assistant Campus Chief'), ('HOD', 'Head of Department'), ('DHOD', 'Deputy Head of Department'), ('MSC_COORD_INFORMATION', 'Program Coordinator, M.Sc. in Informatics and Intelligent Systems Engineering'), ('MSC_COORD_EARTHQUAKE', 'Program Coordinator, M.Sc. in Earthquake Engineering'), ('MSC_COORD_DESIGN', 'Program Coordinator, M.Sc. in Mechanical Design and Manufacturing'), ('EMIS_HEAD', 'Head, Education Management Information Systems'), ('RESEARCH_HEAD', 'Head, Research and Development Unit'), ('MATERIAL_HEAD', 'Head, Material Testing Laboratory'), ('CONSULTANCY_HEAD', 'Head, Consultancy Services'), ('EXAMS_ACADEMIC_HEAD', 'Examination and Academic Administration Head'), ('UNIT_HEAD', 'Head, Unit'), ('SECTION_HEAD', 'Head, Section'), ('UNIT_DEPUTY_HEAD', 'Deputy Head, Unit'), ('SECTION_DEPUTY_HEAD', 'Deputy Head, Section'), ('LIBRARY_HEAD', 'Head, Library Section'), ('FINANCE_HEAD', 'Head, Financial Administation Section'), ('PERSONNEL_HEAD', 'Head, Personnel Section'), ('GENERAL_HEAD', 'Head, General Administration Section'), ('PLANNING_HEAD', 'Head, Planning Section'), ('PROCUREMENT_HEAD', 'Head, Procurement Section'), ('SECURITY_HEAD', 'Head, Security Section'), ('REPAIR_HEAD', 'Head, Repair and Maintenance Section'), ('SPECIAL_SECTION_HEAD', 'Head, Special Section'), ('IQAC_HEAD', 'Head, IQAC Section'), ('SAT_HEAD', 'Head, SAT Section'), ('ADMINISTRATION_HEAD', 'Head, Academic Administration and Exam Section'), ('STORE_HEAD', 'Head, Store Section'), ('ACCOUNT_HEAD', 'Head, Account Section'), ('FACILITIES_HEAD', 'Head, Facilities Section'), ('LECTURER', 'Lecturer'), ('SENIOR_INSTRUCTOR', 'Senior Instructor'), ('TEACHING_ASSISTANCE', 'Teaching Assistance'), ('INSTRUCTOR', 'Instructor'), ('READER', 'Reader'), ('PROFESSOR', 'Professor'), ('ASSOCIATE_PROFESSOR', 'Associate Professor'), ('DEPUTY_INSTRUCTOR', 'Deputy Instructor'), ('ASSISTANT_INSTRUCTOR', 'Assistant Instructor'), ('ASSISTANT_PROFESSOR', 'Assistant Professor'), ('ASSISTANT_FINANCE_CONTROLLER', 'Assistant Finance Controller'), ('DEPUTY_ADM_OFFICER', 'Deputy ADM Officer'), ('DEPUTY_FINANCE_CONTROLLER', 'Deputy Finance Controller'), ('SECTION_OFFICER', 'Section Officer'), ('CHIEF_OFFICE_ASSISTANT', 'Chief Office Assistant'), ('HEAD_ACCOUNT_ASSISTANCE', 'Head Account Assistance'), ('LIBRARY_ASSISTANT', 'Library Assistant'), ('OFFICE_ASSISTANT', 'Office Assistant'), ('TECHNICAL_ASSISTANT', 'Technical Assistant'), ('DRIVER', 'Driver'), ('SENIOR_OFFICE_HELPER', 'Senior Office Helper'), ('OFFICE_HELPER', 'Office Helper'), ('HEAD_TECHNICAL_ASSISTANT', 'Head Technical Assistant'), ('ASSISTANT_STOREKEEPER', 'Assistant Storekeeper'), ('COMPUTER_OPERATOR', 'Computer Operator'), ('LIBRARIAN', 'Librarian'), ('LABORATORY_ASSISTANT', 'Laboratory Assistant'), ('ACCOUNT_OFFICER', 'Account Officer'), ('LIBRARY_INTERN', 'Library Intern'), ('SECURITY_GUARD', 'Security Guard'), ('SISTER', 'Sister')], max_length=100)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Designations',
                'ordering': ['rank'],
                'unique_together': {('designation', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='PlansPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plans and Policy',
                'verbose_name_plural': 'Plans and Policies',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('file', models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])])),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('roll', models.CharField(max_length=255)),
                ('photo', models.FileField(blank=True, null=True, upload_to='media/students/')),
                ('is_cr', models.BooleanField()),
                ('is_topper', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_department', to='department.department')),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('founded_at', models.DateField(blank=True, null=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_department', to='department.department')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_social_media', to='home.socialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('report', models.FileField(upload_to='media/files/project', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])])),
                ('published_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_projects', to='department.department')),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_programs', to='department.department')),
            ],
            options={
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_department', to='department.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='plans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_plans', to='department.planspolicy'),
        ),
        migrations.AddField(
            model_name='department',
            name='social_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_social_media', to='home.socialmedia'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.CharField(max_length=255)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_department', to='department.department')),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('responsibility', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_key_official', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='department.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_person', to='department.designation')),
                ('social_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socials', to='home.socialmedia')),
            ],
            options={
                'verbose_name_plural': 'Staff Members',
                'ordering': ['designation'],
                'unique_together': {('name', 'designation')},
            },
        ),
    ]
