# Generated by Django 4.2.2 on 2025-07-20 10:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('name', models.CharField(help_text='Name of the academic program.', max_length=255, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, help_text='Short name or acronym for the program. (e.g. BEI, BCT)', max_length=50, verbose_name='Short Name')),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Auto-generated slug from the program name.', max_length=255, verbose_name='Slug')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Detailed description of the program.')),
                ('program_type', models.CharField(choices=[('BACHELORS', 'Bachelors'), ('MASTERS', 'Masters')], max_length=20, verbose_name='Program Type')),
                ('thumbnail', models.ImageField(help_text='Image representing the academic program.', null=True, upload_to='department/programs/thumbnails', verbose_name='Program Thumbnail')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Program',
                'verbose_name_plural': 'Academic Programs',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterField(
            model_name='department',
            name='brief_description',
            field=models.TextField(blank=True, help_text='Short introduction about the department.', verbose_name='Introduction'),
        ),
        migrations.AlterField(
            model_name='department',
            name='detailed_description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed information and overview of the department.', verbose_name='Detailed Description'),
        ),
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, help_text='Official email address of the department.', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Official name of the department.', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='phone_no',
            field=models.CharField(blank=True, help_text='Contact phone number of the department.', max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(blank=True, editable=False, help_text='Auto-generated slug from the name.', max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='department',
            name='thumbnail',
            field=models.ImageField(help_text='Image representing the department (used on website).', null=True, upload_to='department/thumbnails', verbose_name='Department Thumbnail'),
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('title', models.CharField(choices=[('ER', 'Er'), ('PROF', 'Prof'), ('DR', 'Dr'), ('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms'), ('ASSOC_PROF', 'Assoc Prof'), ('ASST_PROF', 'Asst Prof'), ('LECTURER', 'Lecturer'), ('TECHNICIAN', 'Technician'), ('OTHER', 'Other')], help_text='Title of the staff member (e.g., Mr., Dr., Prof.).', max_length=50, verbose_name='Title')),
                ('name', models.CharField(help_text='Full name of the staff member.', max_length=100, verbose_name='Name')),
                ('designation', models.CharField(blank=True, choices=[('CAMPUS_CHIEF', 'Campus Chief'), ('ASSIST_CAMPUS_CHIEF_ADMIN', 'Assist Campus Chief Admin'), ('ASSIST_CAMPUS_CHIEF_ACADEMIC', 'Assist Campus Chief Academic'), ('ASSIST_CAMPUS_CHIEF_PLANNING', 'Assist Campus Chief Planning'), ('ASSIST_CAMPUS_CHIEF', 'Assist Campus Chief'), ('HOD', 'Hod'), ('DHOD', 'Dhod'), ('MSC_COORD_INFORMATION', 'Msc Coord Information'), ('MSC_COORD_EARTHQUAKE', 'Msc Coord Earthquake'), ('MSC_COORD_DESIGN', 'Msc Coord Design'), ('EMIS_HEAD', 'Emis Head'), ('RESEARCH_HEAD', 'Research Head'), ('MATERIAL_HEAD', 'Material Head'), ('CONSULTANCY_HEAD', 'Consultancy Head'), ('EXAMS_ACADEMIC_HEAD', 'Exams Academic Head'), ('UNIT_HEAD', 'Unit Head'), ('SECTION_HEAD', 'Section Head'), ('UNIT_DEPUTY_HEAD', 'Unit Deputy Head'), ('SECTION_DEPUTY_HEAD', 'Section Deputy Head'), ('LIBRARY_HEAD', 'Library Head'), ('FINANCE_HEAD', 'Finance Head'), ('PERSONNEL_HEAD', 'Personnel Head'), ('GENERAL_HEAD', 'General Head'), ('PLANNING_HEAD', 'Planning Head'), ('PROCUREMENT_HEAD', 'Procurement Head'), ('SECURITY_HEAD', 'Security Head'), ('REPAIR_HEAD', 'Repair Head'), ('SPECIAL_SECTION_HEAD', 'Special Section Head'), ('IQAC_HEAD', 'Iqac Head'), ('SAT_HEAD', 'Sat Head'), ('ADMINISTRATION_HEAD', 'Administration Head'), ('STORE_HEAD', 'Store Head'), ('ACCOUNT_HEAD', 'Account Head'), ('FACILITIES_HEAD', 'Facilities Head'), ('LECTURER', 'Lecturer'), ('SENIOR_INSTRUCTOR', 'Senior Instructor'), ('TEACHING_ASSISTANCE', 'Teaching Assistance'), ('INSTRUCTOR', 'Instructor'), ('READER', 'Reader'), ('PROFESSOR', 'Professor'), ('ASSOCIATE_PROFESSOR', 'Associate Professor'), ('DEPUTY_INSTRUCTOR', 'Deputy Instructor'), ('ASSISTANT_INSTRUCTOR', 'Assistant Instructor'), ('ASSISTANT_PROFESSOR', 'Assistant Professor'), ('ASSISTANT_FINANCE_CONTROLLER', 'Assistant Finance Controller'), ('DEPUTY_ADM_OFFICER', 'Deputy Adm Officer'), ('DEPUTY_FINANCE_CONTROLLER', 'Deputy Finance Controller'), ('SECTION_OFFICER', 'Section Officer'), ('CHIEF_OFFICE_ASSISTANT', 'Chief Office Assistant'), ('HEAD_ACCOUNT_ASSISTANCE', 'Head Account Assistance'), ('LIBRARY_ASSISTANT', 'Library Assistant'), ('OFFICE_ASSISTANT', 'Office Assistant'), ('TECHNICAL_ASSISTANT', 'Technical Assistant'), ('DRIVER', 'Driver'), ('SENIOR_OFFICE_HELPER', 'Senior Office Helper'), ('OFFICE_HELPER', 'Office Helper'), ('HEAD_TECHNICAL_ASSISTANT', 'Head Technical Assistant'), ('ASSISTANT_STOREKEEPER', 'Assistant Storekeeper'), ('COMPUTER_OPERATOR', 'Computer Operator'), ('LIBRARIAN', 'Librarian'), ('LABORATORY_ASSISTANT', 'Laboratory Assistant'), ('ACCOUNT_OFFICER', 'Account Officer'), ('LIBRARY_INTERN', 'Library Intern'), ('SECURITY_GUARD', 'Security Guard'), ('SISTER', 'Sister')], help_text='Official designation or position.', max_length=100, verbose_name='Designation')),
                ('photo', models.ImageField(help_text='Profile picture of the staff member.', null=True, upload_to='department/programs/staffs', verbose_name='Photo')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number.', max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, help_text='Email address for communication.', max_length=254, verbose_name='Email Address')),
                ('message', ckeditor.fields.RichTextField(blank=True, help_text='Short message from staff (HOD) or profile bio.', verbose_name='Message')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(help_text='Department the staff member is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='department_staffs', to='department.department', verbose_name='Department')),
                ('program', models.ForeignKey(help_text='Academic program the staff member is part of, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_staffs', to='department.academicprogram', verbose_name='Academic Program')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff Members',
            },
        ),
        migrations.CreateModel(
            name='DepartmentSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('TWITTER', 'Twitter'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'Linkedin'), ('YOUTUBE', 'Youtube'), ('GITHUB', 'Github'), ('WEBSITE', 'Website'), ('OTHER', 'Other')], help_text='Select the social media platform.', max_length=20, unique=True, verbose_name='Platform')),
                ('url', models.URLField(help_text='URL to the respective social media profile.', verbose_name='Profile URL')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_social_links', to='department.department', verbose_name='Department')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department Social Media',
                'verbose_name_plural': 'Department Social Medias',
            },
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='department',
            field=models.ForeignKey(help_text='Department this program belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='department_programs', to='department.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='academicprogram',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
