# Generated by Django 4.2.2 on 2025-07-21 04:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.department.constants
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("department", "0004_department_short_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Name of the event or festival.",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description_short",
                    models.TextField(
                        help_text="Brief summary of the event.",
                        max_length=500,
                        verbose_name="Short Description",
                    ),
                ),
                (
                    "description_detailed",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Detailed information, agenda, and activities.",
                        verbose_name="Detailed Description",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CULTURAL", "Cultural"),
                            ("TECHNICAL", "Technical"),
                            ("MUSICAL", "Musical"),
                            ("SPORTS", "Sports"),
                            ("OTHER", "Other"),
                        ],
                        default=src.department.constants.DepartmentEventTypes["OTHER"],
                        help_text="Type of the event.",
                        max_length=20,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "event_start_date",
                    models.DateField(
                        help_text="Date the event start.",
                        null=True,
                        verbose_name="Date",
                    ),
                ),
                (
                    "event_end_date",
                    models.DateField(
                        help_text="Date the event end.", null=True, verbose_name="Date"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        help_text="Main image for the event.",
                        null=True,
                        upload_to="department/events",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department the event is associated with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="department.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Event",
                "verbose_name_plural": "Department Events",
            },
        ),
        migrations.AddField(
            model_name="staffmember",
            name="display_order",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Display Order (ranking) of staffs to display in website.",
                verbose_name="Display Order",
            ),
        ),
        migrations.AlterField(
            model_name="academicprogram",
            name="thumbnail",
            field=models.ImageField(
                help_text="Image representing the academic program.",
                null=True,
                upload_to="department/programs",
                verbose_name="Program Thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[("HOD", "Hod"), ("DHOD", "Dhod"), ("STAFF", "Staff")],
                help_text="Official designation or position.",
                max_length=100,
                verbose_name="Designation",
            ),
        ),
        migrations.AlterField(
            model_name="staffmember",
            name="photo",
            field=models.ImageField(
                help_text="Profile picture of the staff member.",
                null=True,
                upload_to="department/staffs",
                verbose_name="Photo",
            ),
        ),
        migrations.CreateModel(
            name="DepartmentEventGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="department/events", verbose_name="Image"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption for the image.",
                        max_length=255,
                        verbose_name="Caption",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="department.departmentevent",
                        verbose_name="Department Event",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Event Image",
                "verbose_name_plural": "Department Event Gallery",
            },
        ),
        migrations.CreateModel(
            name="DepartmentDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="E.g. Student ID Form, Character Certificate, etc.",
                        max_length=100,
                        verbose_name="Title",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload the form or downloadable file.",
                        null=True,
                        upload_to="department/downloads",
                        verbose_name="File",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, verbose_name="Description"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Department the download file is associated with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="department.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campus Download",
                "verbose_name_plural": "Campus Downloads",
            },
        ),
    ]
