# Generated by Django 4.2.2 on 2025-07-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0006_departmentplanandpolicy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffmember",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HOD", "Hod"),
                    ("DHOD", "Dhod"),
                    ("PROFESSOR", "Professor"),
                    ("ASSOCIATE_PROFESSOR", "Associate Professor"),
                    ("ASSISTANT_PROFESSOR", "Assistant Professor"),
                    ("READER", "Reader"),
                    ("LECTURER", "Lecturer"),
                    ("SENIOR_INSTRUCTOR", "Senior Instructor"),
                    ("INSTRUCTOR", "Instructor"),
                    ("TEACHING_ASSISTANCE", "Teaching Assistance"),
                    ("SECTION_OFFICER", "Section Officer"),
                    ("CHIEF_OFFICE_ASSISTANT", "Chief Office Assistant"),
                    ("HEAD_TECHNICAL_ASSISTANT", "Head Technical Assistant"),
                    ("TECHNICAL_ASSISTANT", "Technical Assistant"),
                    ("LABORATORY_ASSISTANT", "Laboratory Assistant"),
                    ("OFFICE_ASSISTANT", "Office Assistant"),
                    ("COMPUTER_OPERATOR", "Computer Operator"),
                    ("DRIVER", "Driver"),
                    ("SECURITY_GUARD", "Security Guard"),
                    ("OFFICE_HELPER", "Office Helper"),
                ],
                help_text="Official designation or position.",
                max_length=100,
                verbose_name="Designation",
            ),
        ),
    ]
