# Generated by Django 4.2.2 on 2025-07-25 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0007_alter_staffmember_designation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departmentdownload",
            options={
                "verbose_name": "Department Download",
                "verbose_name_plural": "Department Downloads",
            },
        ),
        migrations.AddField(
            model_name="departmentplanandpolicy",
            name="file",
            field=models.FileField(
                help_text="Upload the form or downloadable file.",
                null=True,
                upload_to="department/plans",
                verbose_name="File",
            ),
        ),
        migrations.AlterField(
            model_name="departmentsocialmedia",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to="department.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="departmentsocialmedia",
            name="platform",
            field=models.CharField(
                choices=[
                    ("FACEBOOK", "Facebook"),
                    ("TWITTER", "Twitter"),
                    ("INSTAGRAM", "Instagram"),
                    ("LINKEDIN", "Linkedin"),
                    ("YOUTUBE", "Youtube"),
                    ("GITHUB", "Github"),
                    ("WEBSITE", "Website"),
                    ("OTHER", "Other"),
                ],
                help_text="Select the social media platform.",
                max_length=20,
                verbose_name="Platform",
            ),
        ),
        migrations.AddConstraint(
            model_name="departmentsocialmedia",
            constraint=models.UniqueConstraint(
                fields=("department", "platform"), name="unique_department_platform"
            ),
        ),
    ]
