# Generated by Django 4.2.2 on 2025-11-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0008_alter_departmentdownload_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentevent",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Event venue or location.",
                max_length=200,
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="departmentevent",
            name="registration_link",
            field=models.URLField(
                blank=True,
                help_text="Optional link for event registration or more information.",
                null=True,
                verbose_name="Registration Link",
            ),
        ),
    ]
