# Generated by Django 4.2.2 on 2025-11-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0010_add_approval_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentevent",
            name="is_approved_by_campus",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the campus has approved this event.",
                verbose_name="Approved by Campus",
            ),
        ),
        migrations.AlterField(
            model_name="departmentevent",
            name="is_approved_by_department",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the department has approved this event.",
                verbose_name="Approved by Department",
            ),
        ),
    ]
