# Generated by Django 4.2.2 on 2025-11-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0011_alter_departmentevent_is_approved_by_campus_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffMember',
        ),
    ]
