# Generated by Django 4.2.2 on 2025-11-19 12:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EMISVPSInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('vps_label', models.CharField(help_text='Friendly name for this VPS', max_length=255, unique=True, verbose_name='VPS label')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('affiliated_ports', models.JSONField(blank=True, default=list, help_text="List of ports with service metadata, e.g. [{'port': 22, 'service': 'SSH', 'label': 'Remote Admin'}]", verbose_name='affiliated ports')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EMIS VPS information',
                'verbose_name_plural': 'EMIS VPS information',
                'ordering': ['vps_label'],
            },
        ),
        migrations.CreateModel(
            name='EMISHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('hardware_type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('server', 'Server'), ('firewall', 'Firewall'), ('endpoint', 'Endpoint'), ('other', 'Other')], default='server', max_length=32, verbose_name='hardware type')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='location')),
                ('endpoints', models.JSONField(blank=True, default=list, help_text='List of URLs, ports or services this device exposes.', verbose_name='endpoints')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EMIS hardware',
                'verbose_name_plural': 'EMIS hardware',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('roll_number', models.CharField(help_text='Format example: THA080BCT002', max_length=12, validators=[django.core.validators.RegexValidator(message='Roll number must follow pattern THA080BCT002.', regex='^[A-Z]{3}\\d{3}[A-Z]{3}\\d{3}$')], verbose_name='roll number')),
                ('birth_date', models.DateField(verbose_name='birth date')),
                ('primary_email', models.EmailField(max_length=254, verbose_name='primary email')),
                ('secondary_email', models.EmailField(max_length=254, verbose_name='secondary email')),
                ('request_sequence', models.PositiveSmallIntegerField(default=1, editable=False, help_text='The number of reset attempts already recorded for this roll.', verbose_name='request sequence')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email reset request',
                'verbose_name_plural': 'email reset requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
