# Generated by Django 4.2.2 on 2025-11-20 15:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EMISVPSInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "vps_name",
                    models.CharField(
                        help_text="Human friendly name of the virtual server",
                        max_length=255,
                        unique=True,
                        verbose_name="VPS name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Stable identifier used by automation and IaC",
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("digitalocean", "DigitalOcean"),
                            ("lightsail", "AWS Lightsail"),
                            ("hetzner", "Hetzner"),
                            ("on-prem", "On-premises / Bare Metal"),
                            ("other", "Other"),
                        ],
                        default="digitalocean",
                        max_length=50,
                        verbose_name="provider",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("production", "Production"),
                            ("staging", "Staging"),
                            ("development", "Development"),
                            ("lab", "Lab / Prototype"),
                        ],
                        default="production",
                        max_length=32,
                        verbose_name="environment",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("maintenance", "Maintenance"),
                            ("retired", "Retired"),
                            ("decommissioned", "Decommissioned"),
                        ],
                        default="active",
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("outage", "Outage"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                        verbose_name="health status",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="public IP address"),
                ),
                (
                    "private_ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="private IP address"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        default="N/A",
                        help_text="Datacenter region or rack name",
                        max_length=255,
                        verbose_name="location",
                    ),
                ),
                (
                    "ram_gb",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Total RAM in gigabytes",
                        verbose_name="RAM (GB)",
                    ),
                ),
                (
                    "cpu_cores",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of CPU cores",
                        verbose_name="CPU cores",
                    ),
                ),
                (
                    "storage_gb",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total storage in gigabytes",
                        null=True,
                        verbose_name="Storage (GB)",
                    ),
                ),
                (
                    "storage_type",
                    models.CharField(
                        default="SSD",
                        help_text="SSD, NVMe, HDD, etc.",
                        max_length=50,
                        verbose_name="storage type",
                    ),
                ),
                (
                    "bandwidth_tb",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=5,
                        verbose_name="bandwidth (TB)",
                    ),
                ),
                (
                    "ssh_port",
                    models.PositiveIntegerField(
                        default=22,
                        help_text="Port for secure shell access",
                        verbose_name="SSH port",
                    ),
                ),
                (
                    "operating_system",
                    models.CharField(
                        default="Ubuntu 22.04 LTS",
                        max_length=120,
                        verbose_name="operating system",
                    ),
                ),
                (
                    "kernel_version",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="kernel version"
                    ),
                ),
                (
                    "monitoring_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to Grafana, Uptime Kuma or any monitoring panel",
                        verbose_name="monitoring dashboard",
                    ),
                ),
                (
                    "last_health_check_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last health check"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Free-form labels used for grouping (team, stack, batch, etc.)",
                        verbose_name="tags",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "EMIS VPS information",
                "verbose_name_plural": "EMIS VPS information",
                "ordering": ["vps_name"],
            },
        ),
        migrations.CreateModel(
            name="EMISHardware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "asset_tag",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="Unique inventory tag or barcode ID",
                        max_length=64,
                        unique=True,
                        verbose_name="asset tag",
                    ),
                ),
                (
                    "hardware_type",
                    models.CharField(
                        choices=[
                            ("router", "Router"),
                            ("switch", "Switch"),
                            ("firewall", "Firewall"),
                            ("access_point", "Access Point"),
                            ("modem", "Modem"),
                            ("repeater", "Repeater"),
                            ("bridge", "Bridge"),
                            ("gateway", "Gateway"),
                            ("load_balancer", "Load Balancer"),
                            ("server", "Server"),
                            ("desktop", "Desktop Computer"),
                            ("laptop", "Laptop"),
                            ("tablet", "Tablet"),
                            ("mobile", "Mobile Device"),
                            ("storage", "Storage Array"),
                            ("nas", "Network Attached Storage"),
                            ("san", "Storage Area Network"),
                            ("printer", "Printer"),
                            ("scanner", "Scanner"),
                            ("monitor", "Monitor"),
                            ("projector", "Projector"),
                            ("camera", "Camera"),
                            ("telephone", "Telephone"),
                            ("ups", "UPS / Power"),
                            ("pdu", "Power Distribution Unit"),
                            ("rack", "Server Rack"),
                            ("kvm", "KVM Switch"),
                            ("endpoint", "Endpoint"),
                            ("other", "Other"),
                        ],
                        default="server",
                        max_length=32,
                        verbose_name="hardware type",
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="manufacturer"
                    ),
                ),
                (
                    "model_number",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="model number"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="serial number"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="location"
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("production", "Production"),
                            ("staging", "Staging"),
                            ("development", "Development"),
                            ("lab", "Lab / Prototype"),
                        ],
                        default="production",
                        max_length=32,
                        verbose_name="environment",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("standby", "Standby"),
                            ("maintenance", "Maintenance"),
                            ("retired", "Retired"),
                        ],
                        default="operational",
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                (
                    "responsible_team",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="responsible team"
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="purchase date"
                    ),
                ),
                (
                    "warranty_expires_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="warranty expires at"
                    ),
                ),
                (
                    "power_draw_watts",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="power draw (W)"
                    ),
                ),
                (
                    "rack_unit",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="rack / unit"
                    ),
                ),
                (
                    "thumbnail_image",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail image of the hardware device",
                        null=True,
                        upload_to="emis/hardware/thumbnails/",
                        verbose_name="thumbnail image",
                    ),
                ),
                (
                    "endpoints",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of URLs, ports or services this device exposes.",
                        verbose_name="endpoints",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Hardware specifications like RAM, CPU, storage, etc.",
                        verbose_name="specifications",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Any extra structured data (interfaces, notes, etc.)",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "EMIS hardware",
                "verbose_name_plural": "EMIS hardware",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmailResetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="full name"),
                ),
                (
                    "roll_number",
                    models.CharField(
                        help_text="Format example: THA080BCT002",
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Roll number must follow pattern THA080BCT002.",
                                regex="^[A-Z]{3}\\d{3}[A-Z]{3}\\d{3}$",
                            )
                        ],
                        verbose_name="roll number",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="birth date")),
                (
                    "primary_email",
                    models.EmailField(max_length=254, verbose_name="primary email"),
                ),
                (
                    "secondary_email",
                    models.EmailField(max_length=254, verbose_name="secondary email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        default="9800000000",
                        help_text="Contact phone number for verification",
                        max_length=20,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Current status of the reset request",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "request_sequence",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        help_text="The number of reset attempts already recorded for this roll.",
                        verbose_name="request sequence",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the request was approved or rejected",
                        null=True,
                        verbose_name="processed at",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes from the processing staff member",
                        verbose_name="processing notes",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff member who approved or rejected this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_reset_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="processed by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "email reset request",
                "verbose_name_plural": "email reset requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EMISVPSService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the service (e.g., ecast, portal)",
                        max_length=255,
                        verbose_name="service name",
                    ),
                ),
                (
                    "service_key",
                    models.CharField(
                        help_text="Systemd unit, container name or identifier",
                        max_length=120,
                        verbose_name="service key",
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        help_text="Port number the service runs on", verbose_name="port"
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("http", "HTTP"),
                            ("https", "HTTPS"),
                            ("tcp", "TCP"),
                            ("udp", "UDP"),
                        ],
                        default="http",
                        max_length=10,
                        verbose_name="protocol",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        help_text="Type of service (e.g., ecast.service, nginx.service)",
                        max_length=100,
                        verbose_name="service type",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Domain name for the service (e.g., ecast.tcioe.edu.np)",
                        max_length=255,
                        verbose_name="domain",
                    ),
                ),
                (
                    "is_ssl_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether SSL/TLS is enabled for this service",
                        verbose_name="SSL enabled",
                    ),
                ),
                (
                    "healthcheck_endpoint",
                    models.CharField(
                        blank=True,
                        help_text="Relative path or URL used for heartbeat checks",
                        max_length=255,
                        verbose_name="healthcheck endpoint",
                    ),
                ),
                (
                    "healthcheck_expectation",
                    models.CharField(
                        blank=True,
                        help_text="Expected response (status code, JSON key, etc.)",
                        max_length=255,
                        verbose_name="health expectation",
                    ),
                ),
                (
                    "version",
                    models.CharField(blank=True, max_length=50, verbose_name="version"),
                ),
                (
                    "deploy_strategy",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("gitops", "GitOps"),
                            ("ci_cd", "CI / CD"),
                        ],
                        default="manual",
                        max_length=32,
                        verbose_name="deploy strategy",
                    ),
                ),
                (
                    "auto_restart",
                    models.BooleanField(
                        default=True,
                        help_text="Whether supervisors/systemd restart the service",
                        verbose_name="auto restart",
                    ),
                ),
                (
                    "maintained_by",
                    models.CharField(
                        blank=True,
                        help_text="Owning team or point of contact",
                        max_length=255,
                        verbose_name="maintained by",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("failed", "Failed"),
                            ("deploying", "Deploying"),
                        ],
                        default="running",
                        max_length=32,
                        verbose_name="status",
                    ),
                ),
                (
                    "last_deployed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last deployed at"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Free-form JSON for env vars, scaling hints, etc.",
                        verbose_name="metadata",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="emis.emisvpsinfo",
                        verbose_name="VPS server",
                    ),
                ),
            ],
            options={
                "verbose_name": "VPS service",
                "verbose_name_plural": "VPS services",
                "ordering": ["vps", "port"],
                "unique_together": {
                    ("vps", "name"),
                    ("vps", "port"),
                    ("vps", "service_key"),
                },
            },
        ),
    ]
