# Generated by Django 4.2.2 on 2025-11-23 12:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMISDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(choices=[('report_form', 'Reports & Forms'), ('resource', 'Resources & Downloads')], default='resource', max_length=20, verbose_name='Category')),
                ('file', models.FileField(blank=True, help_text='Upload the downloadable document or form.', null=True, upload_to='emis/downloads/', verbose_name='File')),
                ('link_url', models.URLField(blank=True, help_text='Optional external link if the file is hosted elsewhere.', verbose_name='Link URL')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EMIS download',
                'verbose_name_plural': 'EMIS downloads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EMISNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Summary')),
                ('body', ckeditor.fields.RichTextField(blank=True, verbose_name='Body')),
                ('category', models.CharField(choices=[('security', 'Security Update'), ('maintenance', 'Maintenance'), ('release', 'Release & Feature'), ('advisory', 'Advisory'), ('general', 'General')], default='general', max_length=20, verbose_name='Category')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='info', max_length=20, verbose_name='Severity')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published at')),
                ('is_published', models.BooleanField(default=True, help_text='Unpublish to hide the notice from the public feed.', verbose_name='Published')),
                ('attachment', models.FileField(blank=True, help_text='Optional attachment such as a PDF advisory.', null=True, upload_to='emis/notices/', verbose_name='Attachment')),
                ('external_url', models.URLField(blank=True, help_text='Optional reference link for more details.', verbose_name='External URL')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EMIS notice',
                'verbose_name_plural': 'EMIS notices',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['slug'], name='emis_emisno_slug_f03e24_idx'), models.Index(fields=['category'], name='emis_emisno_categor_40dc27_idx'), models.Index(fields=['severity'], name='emis_emisno_severit_6092de_idx')],
            },
        ),
    ]
