# Generated by Django 4.2.2 on 2025-11-19 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emis", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emisvpsinfo",
            options={
                "ordering": ["vps_name"],
                "verbose_name": "EMIS VPS information",
                "verbose_name_plural": "EMIS VPS information",
            },
        ),
        migrations.RemoveField(
            model_name="emisvpsinfo",
            name="affiliated_ports",
        ),
        migrations.RemoveField(
            model_name="emisvpsinfo",
            name="vps_label",
        ),
        migrations.AddField(
            model_name="emailresetrequest",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes from the processing staff member",
                verbose_name="processing notes",
            ),
        ),
        migrations.AddField(
            model_name="emailresetrequest",
            name="phone_number",
            field=models.CharField(
                default="9800000000",
                help_text="Contact phone number for verification",
                max_length=20,
                verbose_name="phone number",
            ),
        ),
        migrations.AddField(
            model_name="emailresetrequest",
            name="processed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the request was approved or rejected",
                null=True,
                verbose_name="processed at",
            ),
        ),
        migrations.AddField(
            model_name="emailresetrequest",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who approved or rejected this request",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_reset_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="processed by",
            ),
        ),
        migrations.AddField(
            model_name="emailresetrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Current status of the reset request",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="emishardware",
            name="specifications",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Hardware specifications like RAM, CPU, storage, etc.",
                verbose_name="specifications",
            ),
        ),
        migrations.AddField(
            model_name="emishardware",
            name="thumbnail_image",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail image of the hardware device",
                null=True,
                upload_to="emis/hardware/thumbnails/",
                verbose_name="thumbnail image",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="cpu_cores",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of CPU cores", verbose_name="CPU cores"
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="ram_gb",
            field=models.PositiveIntegerField(
                default=1, help_text="Total RAM in gigabytes", verbose_name="RAM (GB)"
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="storage_gb",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total storage in gigabytes",
                null=True,
                verbose_name="Storage (GB)",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="vps_name",
            field=models.CharField(
                default="9800000000",
                help_text="Name of the VPS server",
                max_length=255,
                unique=True,
                verbose_name="VPS name",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="EMISVPSService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the service (e.g., ecast, portal)",
                        max_length=255,
                        verbose_name="service name",
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        help_text="Port number the service runs on", verbose_name="port"
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        help_text="Type of service (e.g., ecast.service, nginx.service)",
                        max_length=100,
                        verbose_name="service type",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Domain name for the service (e.g., ecast.tcioe.edu.np)",
                        max_length=255,
                        verbose_name="domain",
                    ),
                ),
                (
                    "is_ssl_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether SSL/TLS is enabled for this service",
                        verbose_name="SSL enabled",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vps",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="emis.emisvpsinfo",
                        verbose_name="VPS server",
                    ),
                ),
            ],
            options={
                "verbose_name": "VPS service",
                "verbose_name_plural": "VPS services",
                "ordering": ["vps", "port"],
                "unique_together": {("vps", "name"), ("vps", "port")},
            },
        ),
    ]
