# Generated by Django 4.2.2 on 2025-11-20 11:30

import datetime
import uuid

from django.db import migrations, models
from django.utils.text import slugify


def assign_asset_tags(apps, schema_editor):
    Hardware = apps.get_model("emis", "EMISHardware")
    existing = set(
        Hardware.objects.exclude(asset_tag__isnull=True)
        .exclude(asset_tag="")
        .values_list("asset_tag", flat=True)
    )
    for hw in Hardware.objects.all():
        if hw.asset_tag:
            continue
        new_tag = uuid.uuid4().hex[:12]
        while new_tag in existing:
            new_tag = uuid.uuid4().hex[:12]
        hw.asset_tag = new_tag
        hw.save(update_fields=["asset_tag"])
        existing.add(new_tag)


def assign_vps_slugs(apps, schema_editor):
    Vps = apps.get_model("emis", "EMISVPSInfo")
    existing = set(
        Vps.objects.exclude(slug__isnull=True).exclude(slug="").values_list("slug", flat=True)
    )
    for node in Vps.objects.all():
        base = slugify(node.vps_name) or f"vps-{node.pk}"
        candidate = base
        counter = 1
        while candidate in existing:
            candidate = f"{base}-{counter}"
            counter += 1
        node.slug = candidate
        node.save(update_fields=["slug"])
        existing.add(candidate)


def assign_service_keys(apps, schema_editor):
    Service = apps.get_model("emis", "EMISVPSService")
    for svc in Service.objects.all():
        if svc.service_key:
            continue
        base = slugify(svc.name) or "service"
        svc.service_key = f"{base}-{svc.pk}"[:120]
        svc.save(update_fields=["service_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("emis", "0002_update_emis_models"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="emisvpsservice",
            unique_together={("vps", "port"), ("vps", "name")},
        ),
        migrations.AddField(
            model_name="emishardware",
            name="asset_tag",
            field=models.CharField(
                blank=True,
                help_text="Unique inventory tag or barcode ID",
                max_length=64,
                null=True,
                verbose_name="asset tag",
            ),
        ),
        migrations.AddField(
            model_name="emishardware",
            name="environment",
            field=models.CharField(
                choices=[
                    ("production", "Production"),
                    ("staging", "Staging"),
                    ("development", "Development"),
                    ("lab", "Lab / Prototype"),
                ],
                default="production",
                max_length=32,
                verbose_name="environment",
            ),
        ),
        migrations.AddField(
            model_name="emishardware",
            name="manufacturer",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="manufacturer"
            ),
        ),
        migrations.AddField(
            model_name="emishardware",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Any extra structured data (interfaces, notes, etc.)",
                verbose_name="metadata",
            ),
        ),
        migrations.AddField(
            model_name="emishardware",
            name="model_number",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="model number"
            ),
        ),
        migrations.AddField(
            model_name="emishardware",
            name="power_draw_watts",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="power draw (W)"
            ),
        ),
        migrations.AddField(
            model_name="emishardware",
            name="purchase_date",
            field=models.DateField(blank=True, null=True, verbose_name="purchase date"),
        ),
        migrations.AddField(
            model_name="emishardware",
            name="rack_unit",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="rack / unit"
            ),
        ),
        migrations.AddField(
            model_name="emishardware",
            name="responsible_team",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="responsible team"
            ),
        ),
        migrations.AddField(
            model_name="emishardware",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="serial number"
            ),
        ),
        migrations.AddField(
            model_name="emishardware",
            name="status",
            field=models.CharField(
                choices=[
                    ("operational", "Operational"),
                    ("standby", "Standby"),
                    ("maintenance", "Maintenance"),
                    ("retired", "Retired"),
                ],
                default="operational",
                max_length=32,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="emishardware",
            name="warranty_expires_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="warranty expires at"
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="bandwidth_tb",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=5, verbose_name="bandwidth (TB)"
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="environment",
            field=models.CharField(
                choices=[
                    ("production", "Production"),
                    ("staging", "Staging"),
                    ("development", "Development"),
                    ("lab", "Lab / Prototype"),
                ],
                default="production",
                max_length=32,
                verbose_name="environment",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="health_status",
            field=models.CharField(
                choices=[
                    ("healthy", "Healthy"),
                    ("degraded", "Degraded"),
                    ("outage", "Outage"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=32,
                verbose_name="health status",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="kernel_version",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="kernel version"
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="last_health_check_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last health check"
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="location",
            field=models.CharField(
                default="N/A",
                help_text="Datacenter region or rack name",
                max_length=255,
                verbose_name="location",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="monitoring_url",
            field=models.URLField(
                blank=True,
                help_text="Link to Grafana, Uptime Kuma or any monitoring panel",
                verbose_name="monitoring dashboard",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="operating_system",
            field=models.CharField(
                default="Ubuntu 22.04 LTS",
                max_length=120,
                verbose_name="operating system",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="private_ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="private IP address"
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="provider",
            field=models.CharField(
                choices=[
                    ("digitalocean", "DigitalOcean"),
                    ("lightsail", "AWS Lightsail"),
                    ("hetzner", "Hetzner"),
                    ("on-prem", "On-premises / Bare Metal"),
                    ("other", "Other"),
                ],
                default="digitalocean",
                max_length=50,
                verbose_name="provider",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Stable identifier used by automation and IaC",
                null=True,
                verbose_name="slug",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="ssh_port",
            field=models.PositiveIntegerField(
                default=22,
                help_text="Port for secure shell access",
                verbose_name="SSH port",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("maintenance", "Maintenance"),
                    ("retired", "Retired"),
                    ("decommissioned", "Decommissioned"),
                ],
                default="active",
                max_length=32,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="storage_type",
            field=models.CharField(
                default="SSD",
                help_text="SSD, NVMe, HDD, etc.",
                max_length=50,
                verbose_name="storage type",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsinfo",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Free-form labels used for grouping (team, stack, batch, etc.)",
                verbose_name="tags",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsservice",
            name="auto_restart",
            field=models.BooleanField(
                default=True,
                help_text="Whether supervisors/systemd restart the service",
                verbose_name="auto restart",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsservice",
            name="deploy_strategy",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("gitops", "GitOps"),
                    ("ci_cd", "CI / CD"),
                ],
                default="manual",
                max_length=32,
                verbose_name="deploy strategy",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsservice",
            name="healthcheck_endpoint",
            field=models.CharField(
                blank=True,
                help_text="Relative path or URL used for heartbeat checks",
                max_length=255,
                verbose_name="healthcheck endpoint",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsservice",
            name="healthcheck_expectation",
            field=models.CharField(
                blank=True,
                help_text="Expected response (status code, JSON key, etc.)",
                max_length=255,
                verbose_name="health expectation",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsservice",
            name="last_deployed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last deployed at"
            ),
        ),
        migrations.AddField(
            model_name="emisvpsservice",
            name="maintained_by",
            field=models.CharField(
                blank=True,
                help_text="Owning team or point of contact",
                max_length=255,
                verbose_name="maintained by",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsservice",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Free-form JSON for env vars, scaling hints, etc.",
                verbose_name="metadata",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsservice",
            name="protocol",
            field=models.CharField(
                choices=[
                    ("http", "HTTP"),
                    ("https", "HTTPS"),
                    ("tcp", "TCP"),
                    ("udp", "UDP"),
                ],
                default="http",
                max_length=10,
                verbose_name="protocol",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsservice",
            name="service_key",
            field=models.CharField(
                blank=True,
                help_text="Systemd unit, container name or identifier",
                max_length=120,
                null=True,
                verbose_name="service key",
            ),
        ),
        migrations.RunPython(assign_asset_tags, migrations.RunPython.noop),
        migrations.RunPython(assign_vps_slugs, migrations.RunPython.noop),
        migrations.RunPython(assign_service_keys, migrations.RunPython.noop),
        migrations.AddField(
            model_name="emisvpsservice",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("paused", "Paused"),
                    ("failed", "Failed"),
                    ("deploying", "Deploying"),
                ],
                default="running",
                max_length=32,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="emisvpsservice",
            name="version",
            field=models.CharField(blank=True, max_length=50, verbose_name="version"),
        ),
        migrations.AlterField(
            model_name="emishardware",
            name="asset_tag",
            field=models.CharField(
                default=uuid.uuid4,
                help_text="Unique inventory tag or barcode ID",
                max_length=64,
                unique=True,
                verbose_name="asset tag",
            ),
        ),
        migrations.AlterField(
            model_name="emisvpsinfo",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Stable identifier used by automation and IaC",
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="emisvpsservice",
            name="service_key",
            field=models.CharField(
                help_text="Systemd unit, container name or identifier",
                max_length=120,
                verbose_name="service key",
            ),
        ),
        migrations.AlterField(
            model_name="emishardware",
            name="hardware_type",
            field=models.CharField(
                choices=[
                    ("router", "Router"),
                    ("switch", "Switch"),
                    ("server", "Server"),
                    ("firewall", "Firewall"),
                    ("endpoint", "Endpoint"),
                    ("storage", "Storage Array"),
                    ("ups", "UPS / Power"),
                    ("other", "Other"),
                ],
                default="server",
                max_length=32,
                verbose_name="hardware type",
            ),
        ),
        migrations.AlterField(
            model_name="emisvpsinfo",
            name="ip_address",
            field=models.GenericIPAddressField(verbose_name="public IP address"),
        ),
        migrations.AlterField(
            model_name="emisvpsinfo",
            name="ram_gb",
            field=models.PositiveIntegerField(
                default=2, help_text="Total RAM in gigabytes", verbose_name="RAM (GB)"
            ),
        ),
        migrations.AlterField(
            model_name="emisvpsinfo",
            name="vps_name",
            field=models.CharField(
                help_text="Human friendly name of the virtual server",
                max_length=255,
                unique=True,
                verbose_name="VPS name",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emisvpsservice",
            unique_together={("vps", "service_key"), ("vps", "port"), ("vps", "name")},
        ),
    ]
