# Generated by Django 4.2.2 on 2025-11-20 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("emis", "0003_alter_emisvpsservice_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emisvpsinfo",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Stable identifier used by automation and IaC",
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
