# Generated by Django 4.2.2 on 2025-11-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emis", "0004_alter_emisvpsinfo_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emishardware",
            name="hardware_type",
            field=models.CharField(
                choices=[
                    ("router", "Router"),
                    ("switch", "Switch"),
                    ("firewall", "Firewall"),
                    ("access_point", "Access Point"),
                    ("modem", "Modem"),
                    ("repeater", "Repeater"),
                    ("bridge", "Bridge"),
                    ("gateway", "Gateway"),
                    ("load_balancer", "Load Balancer"),
                    ("server", "Server"),
                    ("desktop", "Desktop Computer"),
                    ("laptop", "Laptop"),
                    ("tablet", "Tablet"),
                    ("mobile", "Mobile Device"),
                    ("storage", "Storage Array"),
                    ("nas", "Network Attached Storage"),
                    ("san", "Storage Area Network"),
                    ("printer", "Printer"),
                    ("scanner", "Scanner"),
                    ("monitor", "Monitor"),
                    ("projector", "Projector"),
                    ("camera", "Camera"),
                    ("telephone", "Telephone"),
                    ("ups", "UPS / Power"),
                    ("pdu", "Power Distribution Unit"),
                    ("rack", "Server Rack"),
                    ("kvm", "KVM Switch"),
                    ("endpoint", "Endpoint"),
                    ("other", "Other"),
                ],
                default="server",
                max_length=32,
                verbose_name="hardware type",
            ),
        ),
    ]
