# Generated by Django 4.2.2 on 2025-07-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campuskeyofficial",
            name="title_prefix",
            field=models.CharField(
                choices=[
                    ("ER", "Er"),
                    ("PROF", "Prof"),
                    ("DR", "Dr"),
                    ("MR", "Mr"),
                    ("MRS", "Mrs"),
                    ("MS", "Ms"),
                    ("ASSOC_PROF", "Assoc Prof"),
                    ("ASST_PROF", "Asst Prof"),
                    ("LECTURER", "Lecturer"),
                    ("TECHNICIAN", "Technician"),
                    ("OTHER", "Other"),
                ],
                help_text="E.g., ER, DR, Mr., Ms.",
                max_length=10,
                verbose_name="Title Prefix",
            ),
        ),
    ]
