# Generated by Django 4.2.2 on 2025-07-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_campuskeyofficial_title_prefix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campusevent",
            name="event_date",
        ),
        migrations.AddField(
            model_name="campusevent",
            name="event_end_date",
            field=models.DateField(
                help_text="Date the event end.", null=True, verbose_name="Date"
            ),
        ),
        migrations.AddField(
            model_name="campusevent",
            name="event_start_date",
            field=models.DateField(
                help_text="Date the event start.", null=True, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="campusfeedback",
            name="email",
            field=models.EmailField(
                blank=True, default=1, max_length=254, verbose_name="Email"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="campuskeyofficial",
            name="designation",
            field=models.CharField(
                choices=[
                    ("CAMPUS_CHIEF", "Campus Chief"),
                    ("ASSIST_CAMPUS_CHIEF_ADMIN", "Assist Campus Chief Admin"),
                    ("ASSIST_CAMPUS_CHIEF_ACADEMIC", "Assist Campus Chief Academic"),
                    ("ASSIST_CAMPUS_CHIEF_PLANNING", "Assist Campus Chief Planning"),
                    ("ASSIST_CAMPUS_CHIEF", "Assist Campus Chief"),
                    ("HOD", "Hod"),
                    ("DHOD", "Dhod"),
                    ("MSC_COORD_INFORMATION", "Msc Coord Information"),
                    ("MSC_COORD_EARTHQUAKE", "Msc Coord Earthquake"),
                    ("MSC_COORD_DESIGN", "Msc Coord Design"),
                    ("EMIS_HEAD", "Emis Head"),
                    ("RESEARCH_HEAD", "Research Head"),
                    ("MATERIAL_HEAD", "Material Head"),
                    ("CONSULTANCY_HEAD", "Consultancy Head"),
                    ("EXAMS_ACADEMIC_HEAD", "Exams Academic Head"),
                    ("UNIT_HEAD", "Unit Head"),
                    ("SECTION_HEAD", "Section Head"),
                    ("UNIT_DEPUTY_HEAD", "Unit Deputy Head"),
                    ("SECTION_DEPUTY_HEAD", "Section Deputy Head"),
                    ("LIBRARY_HEAD", "Library Head"),
                    ("FINANCE_HEAD", "Finance Head"),
                    ("PERSONNEL_HEAD", "Personnel Head"),
                    ("GENERAL_HEAD", "General Head"),
                    ("PLANNING_HEAD", "Planning Head"),
                    ("PROCUREMENT_HEAD", "Procurement Head"),
                    ("SECURITY_HEAD", "Security Head"),
                    ("REPAIR_HEAD", "Repair Head"),
                    ("SPECIAL_SECTION_HEAD", "Special Section Head"),
                    ("IQAC_HEAD", "Iqac Head"),
                    ("SAT_HEAD", "Sat Head"),
                    ("ADMINISTRATION_HEAD", "Administration Head"),
                    ("STORE_HEAD", "Store Head"),
                    ("ACCOUNT_HEAD", "Account Head"),
                    ("FACILITIES_HEAD", "Facilities Head"),
                    ("LECTURER", "Lecturer"),
                    ("SENIOR_INSTRUCTOR", "Senior Instructor"),
                    ("TEACHING_ASSISTANCE", "Teaching Assistance"),
                    ("INSTRUCTOR", "Instructor"),
                    ("READER", "Reader"),
                    ("PROFESSOR", "Professor"),
                    ("ASSOCIATE_PROFESSOR", "Associate Professor"),
                    ("DEPUTY_INSTRUCTOR", "Deputy Instructor"),
                    ("ASSISTANT_INSTRUCTOR", "Assistant Instructor"),
                    ("ASSISTANT_PROFESSOR", "Assistant Professor"),
                    ("ASSISTANT_FINANCE_CONTROLLER", "Assistant Finance Controller"),
                    ("DEPUTY_ADM_OFFICER", "Deputy Adm Officer"),
                    ("DEPUTY_FINANCE_CONTROLLER", "Deputy Finance Controller"),
                    ("SECTION_OFFICER", "Section Officer"),
                    ("CHIEF_OFFICE_ASSISTANT", "Chief Office Assistant"),
                    ("HEAD_ACCOUNT_ASSISTANCE", "Head Account Assistance"),
                    ("LIBRARY_ASSISTANT", "Library Assistant"),
                    ("OFFICE_ASSISTANT", "Office Assistant"),
                    ("TECHNICAL_ASSISTANT", "Technical Assistant"),
                    ("DRIVER", "Driver"),
                    ("SENIOR_OFFICE_HELPER", "Senior Office Helper"),
                    ("OFFICE_HELPER", "Office Helper"),
                    ("HEAD_TECHNICAL_ASSISTANT", "Head Technical Assistant"),
                    ("ASSISTANT_STOREKEEPER", "Assistant Storekeeper"),
                    ("COMPUTER_OPERATOR", "Computer Operator"),
                    ("LIBRARIAN", "Librarian"),
                    ("LABORATORY_ASSISTANT", "Laboratory Assistant"),
                    ("ACCOUNT_OFFICER", "Account Officer"),
                    ("LIBRARY_INTERN", "Library Intern"),
                    ("SECURITY_GUARD", "Security Guard"),
                    ("SISTER", "Sister"),
                ],
                help_text="Role or position, e.g., Campus Chief.",
                max_length=100,
                verbose_name="Designation",
            ),
        ),
    ]
