# Generated by Django 4.2.2 on 2025-07-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_campusinfo_options_alter_socialmedialink_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="campuskeyofficial",
            name="display_order",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Display Order (ranking) of staffs to display in website.",
                verbose_name="Display Order",
            ),
        ),
        migrations.AlterField(
            model_name="campuskeyofficial",
            name="designation",
            field=models.CharField(
                choices=[
                    ("CAMPUS_CHIEF", "Campus Chief"),
                    ("ASSIST_CAMPUS_CHIEF_ADMIN", "Assist Campus Chief Admin"),
                    ("ASSIST_CAMPUS_CHIEF_ACADEMIC", "Assist Campus Chief Academic"),
                    ("ASSIST_CAMPUS_CHIEF_PLANNING", "Assist Campus Chief Planning"),
                    ("MSC_COORD_INFORMATION", "Msc Coord Information"),
                    ("MSC_COORD_EARTHQUAKE", "Msc Coord Earthquake"),
                    ("MSC_COORD_DESIGN", "Msc Coord Design"),
                    ("EMIS_HEAD", "Emis Head"),
                    ("RESEARCH_HEAD", "Research Head"),
                    ("CONSULTANCY_HEAD", "Consultancy Head"),
                    ("EXAMS_ACADEMIC_HEAD", "Exams Academic Head"),
                    ("LIBRARY_HEAD", "Library Head"),
                    ("FINANCE_HEAD", "Finance Head"),
                    ("PERSONNEL_HEAD", "Personnel Head"),
                    ("PLANNING_HEAD", "Planning Head"),
                    ("PROCUREMENT_HEAD", "Procurement Head"),
                    ("SECURITY_HEAD", "Security Head"),
                    ("IQAC_HEAD", "Iqac Head"),
                    ("ADMINISTRATION_HEAD", "Administration Head"),
                    ("FACILITIES_HEAD", "Facilities Head"),
                    ("DEPUTY_FINANCE_CONTROLLER", "Deputy Finance Controller"),
                    ("LIBRARIAN", "Librarian"),
                    ("ACCOUNT_OFFICER", "Account Officer"),
                ],
                help_text="Role or position, e.g., Campus Chief.",
                max_length=100,
                verbose_name="Designation",
            ),
        ),
    ]
