# Generated by Django 4.2.2 on 2025-07-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_campuskeyofficial_display_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campusfeedback",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="campusfeedback",
            name="updated_by",
        ),
    ]
