# Generated by Django 4.2.2 on 2025-07-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_remove_campusfeedback_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campuskeyofficial",
            name="message",
            field=models.TextField(blank=True, verbose_name="Message"),
        ),
    ]
