# Generated by Django 4.2.2 on 2025-07-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_campuskeyofficial_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academiccalendar",
            name="year",
        ),
        migrations.AddField(
            model_name="academiccalendar",
            name="end_year",
            field=models.PositiveIntegerField(
                default=2082,
                help_text="End year of the academic calendar (e.g., 2082).",
                verbose_name="End Year",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academiccalendar",
            name="start_year",
            field=models.PositiveIntegerField(
                default=2083,
                help_text="Start year of the academic calendar (e.g., 2081).",
                verbose_name="Start Year",
            ),
            preserve_default=False,
        ),
    ]
