# Generated by Django 4.2.2 on 2025-07-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_remove_academiccalendar_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmedialink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("FACEBOOK", "Facebook"),
                    ("TWITTER", "Twitter"),
                    ("INSTAGRAM", "Instagram"),
                    ("LINKEDIN", "Linkedin"),
                    ("YOUTUBE", "Youtube"),
                    ("GITHUB", "Github"),
                    ("WEBSITE", "Website"),
                    ("OTHER", "Other"),
                ],
                help_text="Select the social media platform.",
                max_length=20,
                verbose_name="Platform",
            ),
        ),
    ]
