# Generated by Django 4.2.2 on 2025-08-07 09:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_alter_socialmedialink_platform"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campusunion",
            name="description",
        ),
        migrations.AddField(
            model_name="campusunion",
            name="detailed_description",
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text="In-depth overview about the unions's mission, activities, and history.",
                verbose_name="Detailed Description",
            ),
        ),
        migrations.AddField(
            model_name="campusunion",
            name="short_description",
            field=models.TextField(
                default="",
                help_text="Brief summary or introduction (max 500 characters).",
                max_length=500,
                verbose_name="Short Description",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="campusunion",
            name="thumbnail",
            field=models.ImageField(
                help_text="Optional representative image or logo of the union.",
                null=True,
                upload_to="website/unions",
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AddField(
            model_name="campusunion",
            name="website_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the club website (optional)",
                null=True,
                verbose_name="Website Link",
            ),
        ),
        migrations.AddField(
            model_name="studentclub",
            name="website_url",
            field=models.URLField(
                blank=True,
                help_text="URL of the club website (optional)",
                null=True,
                verbose_name="Website Link",
            ),
        ),
        migrations.AlterField(
            model_name="academiccalendar",
            name="end_year",
            field=models.PositiveIntegerField(
                choices=[
                    (2075, "2075"),
                    (2076, "2076"),
                    (2077, "2077"),
                    (2078, "2078"),
                    (2079, "2079"),
                    (2080, "2080"),
                    (2081, "2081"),
                    (2082, "2082"),
                    (2083, "2083"),
                    (2084, "2084"),
                    (2085, "2085"),
                    (2086, "2086"),
                    (2087, "2087"),
                    (2088, "2088"),
                    (2089, "2089"),
                    (2090, "2090"),
                ],
                help_text="End year of the academic calendar (e.g., 2082).",
                verbose_name="End Year",
            ),
        ),
        migrations.AlterField(
            model_name="academiccalendar",
            name="start_year",
            field=models.PositiveIntegerField(
                choices=[
                    (2075, "2075"),
                    (2076, "2076"),
                    (2077, "2077"),
                    (2078, "2078"),
                    (2079, "2079"),
                    (2080, "2080"),
                    (2081, "2081"),
                    (2082, "2082"),
                    (2083, "2083"),
                    (2084, "2084"),
                    (2085, "2085"),
                    (2086, "2086"),
                    (2087, "2087"),
                    (2088, "2088"),
                    (2089, "2089"),
                    (2090, "2090"),
                ],
                help_text="Start year of the academic calendar (e.g., 2081).",
                verbose_name="Start Year",
            ),
        ),
        migrations.AlterField(
            model_name="campusevent",
            name="thumbnail",
            field=models.ImageField(
                help_text="Main image for the event.",
                null=True,
                upload_to="website/events",
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="campuseventgallery",
            name="image",
            field=models.ImageField(upload_to="website/events", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="campusinfo",
            name="organization_chart",
            field=models.ImageField(
                blank=True,
                help_text="Image representing campus organizational structure.",
                null=True,
                upload_to="website/files",
                verbose_name="Organization Chart",
            ),
        ),
        migrations.AlterField(
            model_name="campusunionmember",
            name="photo",
            field=models.ImageField(
                help_text="Profile photo of the member.",
                null=True,
                upload_to="website/unions/members",
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="studentclub",
            name="thumbnail",
            field=models.ImageField(
                help_text="Optional representative image or logo of the club.",
                null=True,
                upload_to="website/clubs",
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="studentclubevent",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Representative image for the event.",
                null=True,
                upload_to="website/clubs",
                verbose_name="Event Thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="studentclubeventgallery",
            name="image",
            field=models.ImageField(
                help_text="Upload an image to showcase.",
                upload_to="website/clubs",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="studentclubmember",
            name="photo",
            field=models.ImageField(
                help_text="Profile photo of the member.",
                null=True,
                upload_to="website/clubs/members",
                verbose_name="Photo",
            ),
        ),
    ]
