# Generated by Django 4.2.2 on 2025-11-14 09:58

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0011_alter_campuskeyofficial_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Section Name')),
                ('slug', models.SlugField(help_text='Used for public URLs, e.g. /about/sections/<slug>.', max_length=160, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(help_text='Brief summary shown in listing cards.', max_length=500, verbose_name='Short Description')),
                ('detailed_description', ckeditor.fields.RichTextField(blank=True, help_text='Rich text content describing objectives and responsibilities.', verbose_name='Detailed Description')),
                ('objectives', ckeditor.fields.RichTextField(blank=True, help_text='Bullet list or paragraph describing goals of the section.', verbose_name='Objectives')),
                ('achievements', ckeditor.fields.RichTextField(blank=True, help_text='Optional highlights, milestones or services.', verbose_name='Key Achievements')),
                ('thumbnail', models.ImageField(blank=True, help_text='Image used in listing cards.', null=True, upload_to='website/sections', verbose_name='Thumbnail')),
                ('hero_image', models.ImageField(blank=True, help_text='Large banner image used on the section detail page.', null=True, upload_to='website/sections', verbose_name='Hero Image')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('display_order', models.PositiveSmallIntegerField(default=1, help_text='Controls ordering in menus and listing views.', verbose_name='Display Order')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campus Section',
                'verbose_name_plural': 'Campus Sections',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CampusUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Unit Name')),
                ('slug', models.SlugField(help_text='Used for public URLs, e.g. /about/units/<slug>.', max_length=160, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(help_text='Summary displayed in cards and hero section.', max_length=500, verbose_name='Short Description')),
                ('detailed_description', ckeditor.fields.RichTextField(blank=True, help_text='History, responsibilities and services of the unit.', verbose_name='Detailed Description')),
                ('objectives', ckeditor.fields.RichTextField(blank=True, help_text='List of objectives/goals shown on the public page.', verbose_name='Objectives')),
                ('achievements', ckeditor.fields.RichTextField(blank=True, help_text='Optional achievements, milestones or services.', verbose_name='Key Achievements')),
                ('thumbnail', models.ImageField(blank=True, help_text='Image used in listing cards and menus.', null=True, upload_to='website/units', verbose_name='Thumbnail')),
                ('hero_image', models.ImageField(blank=True, help_text='Primary image displayed on the detail page.', null=True, upload_to='website/units', verbose_name='Hero Image')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name='Display Order')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campus Unit',
                'verbose_name_plural': 'Campus Units',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CampusUnitMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('title_prefix', models.CharField(blank=True, choices=[('ER', 'Er'), ('PROF', 'Prof'), ('DR', 'Dr'), ('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms'), ('ASSOC_PROF', 'Assoc Prof'), ('ASST_PROF', 'Asst Prof'), ('LECTURER', 'Lecturer'), ('TECHNICIAN', 'Technician'), ('OTHER', 'Other')], max_length=10, verbose_name='Title Prefix')),
                ('full_name', models.CharField(max_length=120, verbose_name='Full Name')),
                ('designation', models.CharField(max_length=150, verbose_name='Designation')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='website/units/members', verbose_name='Photo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name='Display Order')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='website.campusunit', verbose_name='Unit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campus Unit Member',
                'verbose_name_plural': 'Campus Unit Members',
                'ordering': ['display_order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='CampusSectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('title_prefix', models.CharField(blank=True, choices=[('ER', 'Er'), ('PROF', 'Prof'), ('DR', 'Dr'), ('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms'), ('ASSOC_PROF', 'Assoc Prof'), ('ASST_PROF', 'Asst Prof'), ('LECTURER', 'Lecturer'), ('TECHNICIAN', 'Technician'), ('OTHER', 'Other')], max_length=10, verbose_name='Title Prefix')),
                ('full_name', models.CharField(max_length=120, verbose_name='Full Name')),
                ('designation', models.CharField(max_length=150, verbose_name='Designation')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='website/sections/members', verbose_name='Photo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('display_order', models.PositiveSmallIntegerField(default=1, verbose_name='Display Order')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='website.campussection', verbose_name='Section')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campus Section Member',
                'verbose_name_plural': 'Campus Section Members',
                'ordering': ['display_order', 'full_name'],
            },
        ),
    ]
