# Generated by Django 4.2.2 on 2025-11-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_campussection_campusunit_campusunitmember_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusunitmember',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='campusunitmember',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='campusunitmember',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='campussection',
            name='designations',
            field=models.JSONField(blank=True, default=list, help_text='Key official designations responsible for this section (uses campus key officials).', verbose_name='Linked Designations'),
        ),
        migrations.AddField(
            model_name='campusunit',
            name='designations',
            field=models.JSONField(blank=True, default=list, help_text='Key official designations responsible for this unit (uses campus key officials).', verbose_name='Linked Designations'),
        ),
        migrations.DeleteModel(
            name='CampusSectionMember',
        ),
        migrations.DeleteModel(
            name='CampusUnitMember',
        ),
    ]
