# Generated by Django 4.2.2 on 2025-11-14 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_campusunitmember_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusunit',
            name='department_head',
            field=models.ForeignKey(blank=True, help_text='Primary person responsible for this unit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_units', to='website.campuskeyofficial'),
        ),
        migrations.AddField(
            model_name='campusunit',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Key officials actively working with this unit.', related_name='campus_units', to='website.campuskeyofficial'),
        ),
        migrations.AlterField(
            model_name='campuskeyofficial',
            name='designation',
            field=models.CharField(choices=[('CAMPUS_CHIEF', 'Campus Chief'), ('ASSIST_CAMPUS_CHIEF_ADMIN', 'Assist Campus Chief Admin'), ('ASSIST_CAMPUS_CHIEF_ACADEMIC', 'Assist Campus Chief Academic'), ('ASSIST_CAMPUS_CHIEF_PLANNING', 'Assist Campus Chief Planning'), ('MSC_COORD_INFORMATION', 'Msc Coord Information'), ('MSC_COORD_EARTHQUAKE', 'Msc Coord Earthquake'), ('MSC_COORD_DESIGN', 'Msc Coord Design'), ('MSC_COORD_MSEQE', 'Msc Coord Mseqe'), ('MSC_COORD_MSIS', 'Msc Coord Msis'), ('MSC_COORD_MSISE', 'Msc Coord Msise'), ('MSC_COORD_MSEDM', 'Msc Coord Msedm'), ('HEAD_OF_INDUSTRIAL_DEPARTMENT', 'Head Of Industrial Department'), ('HEAD_OF_ARCHITECTURE_DEPARTMENT', 'Head Of Architecture Department'), ('HEAD_OF_APPLIED_SCIENCE_DEPARTMENT', 'Head Of Applied Science Department'), ('HEAD_OF_AUTOMOBILE_AND_MECHANICAL_DEPARTMENT', 'Head Of Automobile And Mechanical Department'), ('HEAD_OF_ELECTRONICS_AND_COMPUTER_DEPARTMENT', 'Head Of Electronics And Computer Department'), ('HEAD_OF_CIVIL_DEPARTMENT', 'Head Of Civil Department'), ('EMIS_HEAD', 'Emis Head'), ('RESEARCH_HEAD', 'Research Head'), ('HEAD_OF_RESEARCH_AND_DEVELOPMENT', 'Head Of Research And Development'), ('CONSULTANCY_HEAD', 'Consultancy Head'), ('EXAMS_ACADEMIC_HEAD', 'Exams Academic Head'), ('LIBRARY_HEAD', 'Library Head'), ('FINANCE_HEAD', 'Finance Head'), ('PERSONNEL_HEAD', 'Personnel Head'), ('PLANNING_HEAD', 'Planning Head'), ('PROCUREMENT_HEAD', 'Procurement Head'), ('SECURITY_HEAD', 'Security Head'), ('IQAC_HEAD', 'Iqac Head'), ('ADMINISTRATION_HEAD', 'Administration Head'), ('FACILITIES_HEAD', 'Facilities Head'), ('HEAD_OF_MATERIAL_TESTING_LAB', 'Head Of Material Testing Lab'), ('HEAD_OF_STORE_SECTION', 'Head Of Store Section'), ('HEAD_OF_FINANCE_ADMINISTRATION_SECTION', 'Head Of Finance Administration Section'), ('HEAD_OF_EMIS_UNIT', 'Head Of Emis Unit'), ('HEAD_OF_SAT', 'Head Of Sat'), ('DEPUTY_HEAD_OF_APPLIED_SCIENCE_DEPARTMENT', 'Deputy Head Of Applied Science Department'), ('DEPUTY_HEAD_OF_ARCHITECTURE_DEPARTMENT', 'Deputy Head Of Architecture Department'), ('DEPUTY_HEAD_OF_AUTOMOBILE_AND_MECHANICAL_DEPARTMENT', 'Deputy Head Of Automobile And Mechanical Department'), ('DEPUTY_HEAD_OF_ELECTRONICS_AND_COMPUTER_DEPARTMENT', 'Deputy Head Of Electronics And Computer Department'), ('DEPUTY_HEAD_OF_CIVIL_DEPARTMENT', 'Deputy Head Of Civil Department'), ('DEPUTY_FINANCE_CONTROLLER', 'Deputy Finance Controller'), ('LIBRARIAN', 'Librarian'), ('ACCOUNT_OFFICER', 'Account Officer')], help_text='Role or position, e.g., Campus Chief.', max_length=100, verbose_name='Designation'),
        ),
    ]
