# Generated by Django 4.2.2 on 2025-11-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_campusunit_department_head_campusunit_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campussection',
            name='department_head',
            field=models.ForeignKey(blank=True, help_text='Primary key official leading this section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_sections', to='website.campuskeyofficial'),
        ),
        migrations.AddField(
            model_name='campussection',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Key officials actively assigned to this section.', related_name='campus_sections', to='website.campuskeyofficial'),
        ),
    ]
