# Generated by Django 4.2.2 on 2025-11-14 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid

DEFAULT_DESIGNATIONS = [
    ("CAMPUS_CHIEF", "Campus Chief"),
    ("ASSIST_CAMPUS_CHIEF_ADMIN", "Assist Campus Chief Admin"),
    ("ASSIST_CAMPUS_CHIEF_ACADEMIC", "Assist Campus Chief Academic"),
    ("ASSIST_CAMPUS_CHIEF_PLANNING", "Assist Campus Chief Planning"),
    ("MSC_COORD_INFORMATION", "Msc Coord Information"),
    ("MSC_COORD_EARTHQUAKE", "Msc Coord Earthquake"),
    ("MSC_COORD_DESIGN", "Msc Coord Design"),
    ("MSC_COORD_MSEQE", "Msc Coord Mseqe"),
    ("MSC_COORD_MSIS", "Msc Coord Msis"),
    ("MSC_COORD_MSISE", "Msc Coord Msise"),
    ("MSC_COORD_MSEDM", "Msc Coord Msedm"),
    ("HEAD_OF_INDUSTRIAL_DEPARTMENT", "Head Of Industrial Department"),
    ("HEAD_OF_ARCHITECTURE_DEPARTMENT", "Head Of Architecture Department"),
    ("HEAD_OF_APPLIED_SCIENCE_DEPARTMENT", "Head Of Applied Science Department"),
    (
        "HEAD_OF_AUTOMOBILE_AND_MECHANICAL_DEPARTMENT",
        "Head Of Automobile And Mechanical Department",
    ),
    (
        "HEAD_OF_ELECTRONICS_AND_COMPUTER_DEPARTMENT",
        "Head Of Electronics And Computer Department",
    ),
    ("HEAD_OF_CIVIL_DEPARTMENT", "Head Of Civil Department"),
    ("EMIS_HEAD", "Emis Head"),
    ("RESEARCH_HEAD", "Research Head"),
    ("HEAD_OF_RESEARCH_AND_DEVELOPMENT", "Head Of Research And Development"),
    ("CONSULTANCY_HEAD", "Consultancy Head"),
    ("EXAMS_ACADEMIC_HEAD", "Exams Academic Head"),
    ("LIBRARY_HEAD", "Library Head"),
    ("FINANCE_HEAD", "Finance Head"),
    ("PERSONNEL_HEAD", "Personnel Head"),
    ("PLANNING_HEAD", "Planning Head"),
    ("PROCUREMENT_HEAD", "Procurement Head"),
    ("SECURITY_HEAD", "Security Head"),
    ("IQAC_HEAD", "Iqac Head"),
    ("ADMINISTRATION_HEAD", "Administration Head"),
    ("FACILITIES_HEAD", "Facilities Head"),
    ("HEAD_OF_MATERIAL_TESTING_LAB", "Head Of Material Testing Lab"),
    ("HEAD_OF_STORE_SECTION", "Head Of Store Section"),
    ("HEAD_OF_FINANCE_ADMINISTRATION_SECTION", "Head Of Finance Administration Section"),
    ("HEAD_OF_EMIS_UNIT", "Head Of Emis Unit"),
    ("HEAD_OF_SAT", "Head Of Sat"),
    (
        "DEPUTY_HEAD_OF_APPLIED_SCIENCE_DEPARTMENT",
        "Deputy Head Of Applied Science Department",
    ),
    (
        "DEPUTY_HEAD_OF_ARCHITECTURE_DEPARTMENT",
        "Deputy Head Of Architecture Department",
    ),
    (
        "DEPUTY_HEAD_OF_AUTOMOBILE_AND_MECHANICAL_DEPARTMENT",
        "Deputy Head Of Automobile And Mechanical Department",
    ),
    (
        "DEPUTY_HEAD_OF_ELECTRONICS_AND_COMPUTER_DEPARTMENT",
        "Deputy Head Of Electronics And Computer Department",
    ),
    ("DEPUTY_HEAD_OF_CIVIL_DEPARTMENT", "Deputy Head Of Civil Department"),
    ("DEPUTY_FINANCE_CONTROLLER", "Deputy Finance Controller"),
    ("LIBRARIAN", "Librarian"),
    ("ACCOUNT_OFFICER", "Account Officer"),
]


def assign_staff_designations(apps, schema_editor):
    CampusStaffDesignation = apps.get_model("website", "CampusStaffDesignation")
    CampusKeyOfficial = apps.get_model("website", "CampusKeyOfficial")

    # map existing codes to ensure stable ordering
    order_map = {code: index + 1 for index, (code, _) in enumerate(DEFAULT_DESIGNATIONS)}
    title_map = dict(DEFAULT_DESIGNATIONS)
    extra_order = len(order_map)

    designations_by_code = {
        designation.code: designation
        for designation in CampusStaffDesignation.objects.all()
    }

    for staff in CampusKeyOfficial.objects.exclude(legacy_designation__isnull=True):
        code = staff.legacy_designation
        if not code:
            continue

        designation = designations_by_code.get(code)
        if not designation:
            display_title = title_map.get(code, code.replace("_", " ").title())
            display_order = order_map.get(code)
            if display_order is None:
                extra_order += 1
                display_order = extra_order
                order_map[code] = display_order

            designation = CampusStaffDesignation.objects.create(
                title=display_title,
                code=code,
                description="",
                display_order=display_order,
                is_active=True,
                created_by=staff.created_by,
                updated_by=staff.created_by,
            )
            designations_by_code[code] = designation

        staff.designation = designation
        staff.save(update_fields=["designation"])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0015_campussection_department_head_campussection_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='campuskeyofficial',
            name='is_key_official',
            field=models.BooleanField(default=True, help_text='Mark true if this staff member should appear in key official listings.', verbose_name='Is Key Official'),
        ),
        migrations.CreateModel(
            name='CampusStaffDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('title', models.CharField(help_text='Human readable name of the designation, e.g., Campus Chief.', max_length=150, unique=True, verbose_name='Title')),
                ('code', models.CharField(help_text='System identifier generated from the title (used in APIs and references).', max_length=150, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, help_text='Optional notes about the responsibilities of this designation.', verbose_name='Description')),
                ('display_order', models.PositiveSmallIntegerField(default=1, help_text='Ordering weight when listing designations.', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive designations will be hidden from selection lists.', verbose_name='Is Active')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campus Designation',
                'verbose_name_plural': 'Campus Designations',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.RenameField(
            model_name='campuskeyofficial',
            old_name='designation',
            new_name='legacy_designation',
        ),
        migrations.AddField(
            model_name='campuskeyofficial',
            name='designation',
            field=models.ForeignKey(blank=True, help_text='Select the role for this staff member.', limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='website.campusstaffdesignation', verbose_name='Designation'),
        ),
        migrations.RunPython(assign_staff_designations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='campuskeyofficial',
            name='legacy_designation',
        ),
        migrations.AlterField(
            model_name='campuskeyofficial',
            name='designation',
            field=models.ForeignKey(help_text='Select the role for this staff member.', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='website.campusstaffdesignation', verbose_name='Designation'),
        ),
    ]
