# Generated by Django 4.2.2 on 2025-11-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_campuskeyofficial_is_key_official_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campussection",
            name="designations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Staff designations responsible for this section (uses campus staff records).",
                verbose_name="Linked Designations",
            ),
        ),
        migrations.AlterField(
            model_name="campusunit",
            name="designations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Staff designations responsible for this unit (uses campus staff records).",
                verbose_name="Linked Designations",
            ),
        ),
    ]
