# Generated by Django 4.2.2 on 2025-11-14 18:23

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0017_alter_campussection_designations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campuskeyofficial',
            options={'verbose_name': 'Campus Key Staffs', 'verbose_name_plural': 'Campus Staffs'},
        ),
        migrations.CreateModel(
            name='ResearchFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('name', models.CharField(help_text='Name of the research facility.', max_length=200, unique=True, verbose_name='Facility Name')),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated slug used for URLs.', max_length=220, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, help_text='Brief summary displayed in listings.', max_length=500, verbose_name='Short Description')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Full description for the facility.', verbose_name='Description')),
                ('objectives', ckeditor.fields.RichTextField(blank=True, help_text='Key goals or focus areas for the facility.', verbose_name='Objectives')),
                ('thumbnail', models.ImageField(blank=True, help_text='Image used in listings and detail view.', null=True, upload_to='website/research-facilities', verbose_name='Image')),
                ('display_order', models.PositiveSmallIntegerField(default=1, help_text='Ordering weight for public listings.', verbose_name='Display Order')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research Facility',
                'verbose_name_plural': 'Research Facilities',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
