# Generated by Django 4.2.2 on 2025-11-15 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_alter_departmentdownload_options_and_more'),
        ('website', '0018_alter_campuskeyofficial_options_researchfacility'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusevent',
            name='union',
            field=models.ForeignKey(blank=True, help_text='Union associated with this campus event (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='website.campusunion', verbose_name='Union'),
        ),
        migrations.AddField(
            model_name='campusunion',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Optional department associated with this union.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_unions', to='department.department', verbose_name='Linked Department'),
        ),
        migrations.AddField(
            model_name='studentclub',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Optional department associated with this student club.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_clubs', to='department.department', verbose_name='Linked Department'),
        ),
    ]
