# Generated by Django 4.2.2 on 2025-11-15 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0008_alter_departmentdownload_options_and_more'),
        ('website', '0019_campusevent_union_campusunion_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalGalleryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('title', models.CharField(blank=True, help_text='Optional name for the gallery collection.', max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Additional notes to describe the collection.', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive galleries will be hidden from public listings.', verbose_name='Is Active')),
                ('campus_event', models.ForeignKey(blank=True, help_text='Associate this collection with a campus-wide event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_collections', to='website.campusevent', verbose_name='Campus Event')),
                ('club', models.ForeignKey(blank=True, help_text='Optional student club linked to the gallery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_collections', to='website.studentclub', verbose_name='Student Club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Optional department linked to the gallery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_collections', to='department.department', verbose_name='Department')),
                ('department_event', models.ForeignKey(blank=True, help_text='Associate this collection with a department event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_collections', to='department.departmentevent', verbose_name='Department Event')),
                ('student_club_event', models.ForeignKey(blank=True, help_text='Associate this collection with a club event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_collections', to='website.studentclubevent', verbose_name='Student Club Event')),
                ('union', models.ForeignKey(blank=True, help_text='Optional student union linked to the gallery.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_collections', to='website.campusunion', verbose_name='Union')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Collection',
                'verbose_name_plural': 'Gallery Collections',
            },
        ),
        migrations.CreateModel(
            name='GlobalGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('image', models.ImageField(help_text='Upload an image for this gallery item.', upload_to='website/global-gallery', verbose_name='Image')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=255, verbose_name='Caption')),
                ('display_order', models.PositiveSmallIntegerField(default=1, help_text='Controls the ordering of images within the collection.', verbose_name='Display Order')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.globalgallerycollection', verbose_name='Gallery Collection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
