# Generated by Django on 2025-12-01 00:00

from ckeditor.fields import RichTextField
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0008_alter_departmentdownload_options_and_more'),
        ('website', '0020_globalgallerycollection_globalgalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid', help_text='Represents unique uuid.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='active', help_text='Designates whether this object should be treated as active.')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived', help_text='Designates whether this object should be treated as deleted.')),
                ('title', models.CharField(max_length=255, verbose_name='Event Title', help_text='Name of the event.')),
                ('description', RichTextField(blank=True, verbose_name='Description', help_text='Detail the event activities and insights.')),
                ('event_type', models.CharField(choices=[('CULTURAL', 'CULTURAL'), ('TECHNICAL', 'TECHNICAL'), ('MUSICAL', 'MUSICAL'), ('SPORTS', 'SPORTS'), ('OTHER', 'OTHER')], default='OTHER', max_length=20, verbose_name='Event Type', help_text='Type of the event.')),
                ('event_start_date', models.DateField(blank=True, null=True, verbose_name='Event Start Date', help_text='Date when the event starts.')),
                ('event_end_date', models.DateField(blank=True, null=True, verbose_name='Event End Date', help_text='Date when the event ends.')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='website/global-events', verbose_name='Thumbnail', help_text='Representative banner for the event.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='globalevent_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='globalevent_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Event',
                'verbose_name_plural': 'Global Events',
            },
        ),
        migrations.AddField(
            model_name='globalevent',
            name='clubs',
            field=models.ManyToManyField(blank=True, help_text='Associate student clubs with this event.', related_name='global_events', to='website.studentclub', verbose_name='Linked Clubs'),
        ),
        migrations.AddField(
            model_name='globalevent',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Associate departments with this event.', related_name='global_events', to='department.department', verbose_name='Linked Departments'),
        ),
        migrations.AddField(
            model_name='globalevent',
            name='unions',
            field=models.ManyToManyField(blank=True, help_text='Associate unions with this event.', related_name='global_events', to='website.campusunion', verbose_name='Linked Unions'),
        ),
        migrations.AddField(
            model_name='globalgallerycollection',
            name='global_event',
            field=models.ForeignKey(blank=True, help_text='Associate this collection with a global event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_collections', to='website.globalevent', verbose_name='Global Event'),
        ),
    ]
