# Generated by Django 4.2.2 on 2025-11-15 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.website.constants


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0021_global_event_and_gallery_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalevent",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="globalevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("CULTURAL", "Cultural"),
                    ("TECHNICAL", "Technical"),
                    ("MUSICAL", "Musical"),
                    ("SPORTS", "Sports"),
                    ("OTHER", "Other"),
                ],
                default=src.website.constants.CampusEventTypes["OTHER"],
                help_text="Type of the event.",
                max_length=20,
                verbose_name="Event Type",
            ),
        ),
        migrations.AlterField(
            model_name="globalevent",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="globalevent",
            name="is_archived",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                verbose_name="archived",
            ),
        ),
        migrations.AlterField(
            model_name="globalevent",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
