# Generated by Django on YYYY-MM-DD HH:MM

import django.db.models.deletion
from django.db import migrations, models


def _determine_source_type(collection):
    if collection.campus_event:
        if getattr(collection.campus_event, "union", None):
            return "union_event"
        return "campus_event"
    if collection.student_club_event:
        return "club_event"
    if collection.department_event:
        return "department_event"
    if collection.global_event:
        return "global_event"
    if collection.union:
        return "union_gallery"
    if collection.club:
        return "club_gallery"
    if collection.department:
        return "department_gallery"
    return "college"


def populate_gallery_image_sources(apps, schema_editor):
    GlobalGalleryImage = apps.get_model("website", "GlobalGalleryImage")
    GlobalGalleryCollection = apps.get_model("website", "GlobalGalleryCollection")

    images = (
        GlobalGalleryImage.objects.filter(collection__isnull=False)
        .select_related("collection", "collection__campus_event", "collection__student_club_event",
                        "collection__department_event", "collection__global_event", "collection__union",
                        "collection__club", "collection__department")
    )
    for image in images:
        collection = image.collection
        image.campus_event_id = collection.campus_event_id
        image.student_club_event_id = collection.student_club_event_id
        image.department_event_id = collection.department_event_id
        image.global_event_id = collection.global_event_id
        image.union_id = collection.union_id
        image.club_id = collection.club_id
        image.department_id = collection.department_id
        image.source_title = collection.title or ""
        image.source_context = collection.description or ""
        image.source_type = _determine_source_type(collection)
        image.save(
            update_fields=[
                "campus_event_id",
                "student_club_event_id",
                "department_event_id",
                "global_event_id",
                "union_id",
                "club_id",
                "department_id",
                "source_title",
                "source_context",
                "source_type",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0022_alter_globalevent_created_by_and_more"),
        ("department", "0008_alter_departmentdownload_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalgalleryimage",
            name="campus_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="global_gallery_images",
                to="website.campusevent",
                verbose_name="Campus Event",
            ),
        ),
        migrations.AddField(
            model_name="globalgalleryimage",
            name="student_club_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="global_gallery_images",
                to="website.studentclubevent",
                verbose_name="Student Club Event",
            ),
        ),
        migrations.AddField(
            model_name="globalgalleryimage",
            name="department_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="global_gallery_images",
                to="department.departmentevent",
                verbose_name="Department Event",
            ),
        ),
        migrations.AddField(
            model_name="globalgalleryimage",
            name="union",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="global_gallery_images",
                to="website.campusunion",
                verbose_name="Union",
            ),
        ),
        migrations.AddField(
            model_name="globalgalleryimage",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="global_gallery_images",
                to="website.studentclub",
                verbose_name="Student Club",
            ),
        ),
        migrations.AddField(
            model_name="globalgalleryimage",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="global_gallery_images",
                to="department.department",
                verbose_name="Department",
            ),
        ),
        migrations.AddField(
            model_name="globalgalleryimage",
            name="global_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="global_gallery_images",
                to="website.globalevent",
                verbose_name="Global Event",
            ),
        ),
        migrations.AddField(
            model_name="globalgalleryimage",
            name="source_context",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional context shown alongside this image.",
                max_length=255,
                verbose_name="Source Context",
            ),
        ),
        migrations.AddField(
            model_name="globalgalleryimage",
            name="source_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional title or headline describing the source.",
                max_length=255,
                verbose_name="Source Title",
            ),
        ),
        migrations.AddField(
            model_name="globalgalleryimage",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("campus_event", "Campus Event"),
                    ("union_event", "Union Event"),
                    ("club_event", "Student Club Event"),
                    ("department_event", "Department Event"),
                    ("global_event", "Global Event"),
                    ("union_gallery", "Union Gallery"),
                    ("club_gallery", "Club Gallery"),
                    ("department_gallery", "Department Gallery"),
                    ("college", "College Gallery"),
                    ("custom", "Custom Gallery"),
                ],
                default="college",
                help_text="Primary source category applied to this image.",
                max_length=32,
                verbose_name="Source Type",
            ),
        ),
        migrations.RunPython(
            populate_gallery_image_sources,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="globalgalleryimage",
            name="collection",
        ),
        migrations.DeleteModel(
            name="GlobalGalleryCollection",
        ),
    ]
