# Generated by Django 4.2.2 on 2025-11-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0008_alter_departmentdownload_options_and_more"),
        ("website", "0023_globalgalleryimage_refactor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="globalgalleryimage",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="global_gallery_images",
                to="department.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="globalgalleryimage",
            name="department_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="global_gallery_images",
                to="department.departmentevent",
                verbose_name="Department Event",
            ),
        ),
        migrations.AlterField(
            model_name="globalgalleryimage",
            name="source_context",
            field=models.CharField(
                blank=True,
                help_text="Optional context shown alongside this image.",
                max_length=255,
                verbose_name="Source Context",
            ),
        ),
        migrations.AlterField(
            model_name="globalgalleryimage",
            name="source_title",
            field=models.CharField(
                blank=True,
                help_text="Optional title or headline describing the source.",
                max_length=255,
                verbose_name="Source Title",
            ),
        ),
    ]
