# Generated by Django 4.2.2 on 2025-11-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0024_alter_globalgalleryimage_department_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campuseventgallery",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="campuseventgallery",
            name="event",
        ),
        migrations.RemoveField(
            model_name="campuseventgallery",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="studentclubevent",
            name="club",
        ),
        migrations.RemoveField(
            model_name="studentclubevent",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="studentclubevent",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="studentclubeventgallery",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="studentclubeventgallery",
            name="event",
        ),
        migrations.RemoveField(
            model_name="studentclubeventgallery",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="globalgalleryimage",
            name="campus_event",
        ),
        migrations.RemoveField(
            model_name="globalgalleryimage",
            name="department_event",
        ),
        migrations.RemoveField(
            model_name="globalgalleryimage",
            name="student_club_event",
        ),
        migrations.AddField(
            model_name="globalevent",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Event venue or location.",
                max_length=200,
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="globalevent",
            name="registration_link",
            field=models.URLField(
                blank=True,
                help_text="Optional link for event registration or more information.",
                null=True,
                verbose_name="Registration Link",
            ),
        ),
        migrations.AlterField(
            model_name="globalgalleryimage",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("campus_event", "Campus Event"),
                    ("union_event", "Union Event"),
                    ("club_event", "Student Club Event"),
                    ("global_event", "Global Event"),
                    ("union_gallery", "Union Gallery"),
                    ("club_gallery", "Club Gallery"),
                    ("department_gallery", "Department Gallery"),
                    ("college", "College Gallery"),
                    ("custom", "Custom Gallery"),
                ],
                default="college",
                help_text="Primary source category applied to this image.",
                max_length=32,
                verbose_name="Source Type",
            ),
        ),
        migrations.DeleteModel(
            name="CampusEvent",
        ),
        migrations.DeleteModel(
            name="CampusEventGallery",
        ),
        migrations.DeleteModel(
            name="StudentClubEvent",
        ),
        migrations.DeleteModel(
            name="StudentClubEventGallery",
        ),
    ]
