# Generated by Django 4.2.2 on 2025-11-17 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0025_remove_campuseventgallery_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalgalleryimage",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="global_gallery_images",
                to="website.campussection",
                verbose_name="Campus Section",
            ),
        ),
        migrations.AddField(
            model_name="globalgalleryimage",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="global_gallery_images",
                to="website.campusunit",
                verbose_name="Campus Unit",
            ),
        ),
        migrations.AlterField(
            model_name="globalgalleryimage",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("campus_event", "Campus Event"),
                    ("union_event", "Union Event"),
                    ("club_event", "Student Club Event"),
                    ("global_event", "Global Event"),
                    ("union_gallery", "Union Gallery"),
                    ("club_gallery", "Club Gallery"),
                    ("department_gallery", "Department Gallery"),
                    ("unit_gallery", "Campus Unit Gallery"),
                    ("section_gallery", "Campus Section Gallery"),
                    ("college", "College Gallery"),
                    ("custom", "Custom Gallery"),
                ],
                default="college",
                help_text="Primary source category applied to this image.",
                max_length=32,
                verbose_name="Source Type",
            ),
        ),
    ]
