# Generated by Django 4.2.2 on 2025-11-18 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0012_delete_staffmember'),
        ('website', '0028_alter_globalevent_is_approved_by_campus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campuskeyofficial',
            options={'ordering': ['display_order', 'full_name'], 'verbose_name': 'Campus Staff', 'verbose_name_plural': 'Campus Staff'},
        ),
        migrations.AddField(
            model_name='campuskeyofficial',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department the staff member is associated with (if applicable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='department.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='campuskeyofficial',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Academic program the staff member is part of (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='department.academicprogram', verbose_name='Academic Program'),
        ),
    ]
