# Generated by Django 4.2.2 on 2025-11-18 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_campuskeyofficial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campuskeyofficial',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Administrative unit the staff member is associated with (if applicable).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='website.campusunit', verbose_name='Campus Unit'),
        ),
    ]
