# Generated by Django 4.2.2 on 2025-11-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_add_unit_to_campus_key_official'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campuskeyofficial',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
    ]
