# Generated by Django 4.2.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0031_increase_full_name_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campusstaffdesignation",
            name="display_order",
        ),
        migrations.AlterModelOptions(
            name="campusstaffdesignation",
            options={
                "ordering": ["title"],
                "verbose_name": "Campus Designation",
                "verbose_name_plural": "Campus Designations",
            },
        ),
    ]
