# Generated by Django 4.2.2 on 2025-11-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0032_alter_campuskeyofficial_title_prefix"),
        ("website", "0032_remove_campusstaffdesignation_display_order"),
    ]

    operations = []
