# Generated by Django 4.2.2 on 2025-11-22 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0033_merge_20251119_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusfeedback',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the feedback was marked resolved.', null=True, verbose_name='Resolved At'),
        ),
        migrations.AddField(
            model_name='campusfeedback',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='User who resolved the feedback.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_campus_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Resolved By'),
        ),
        migrations.AddField(
            model_name='campusfeedback',
            name='response_message',
            field=models.TextField(blank=True, help_text='Admin reply that will be emailed back to the submitter.', verbose_name='Response Message'),
        ),
    ]
