# Generated by Django 4.2.2 on 2025-11-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0035_campuskeyofficial_campus_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="campusstaffdesignation",
            name="allow_appointments",
            field=models.BooleanField(
                default=False,
                help_text="Whether this designation should have appointment booking functionality",
                verbose_name="Allow Appointments",
            ),
        ),
        migrations.AddField(
            model_name="campusstaffdesignation",
            name="appointment_priority",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Priority order for appointment categories (lower number = higher priority)",
                null=True,
                verbose_name="Appointment Priority",
            ),
        ),
    ]
