# Generated by Django 4.2.2 on 2025-07-16 08:15

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.notice.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('slug', models.SlugField(help_text='A unique, URL-friendly identifier for this object. ', max_length=255, verbose_name='Slug')),
                ('title', models.CharField(blank=True, help_text='Title of the notice.', max_length=200, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Optional detailed content or body of the notice.', verbose_name='Description')),
                ('thumbnail', models.ImageField(help_text='Optional image representing the notice.', null=True, upload_to='notice/thumbnails', verbose_name='Thumbnail')),
                ('notice_type', models.CharField(choices=[('DEPARTMENT', 'Department'), ('ADMINISTRATION', 'Administration'), ('ADMISSION', 'Admission'), ('EXAMINATION', 'Exam'), ('SCHOLARSHIP', 'Scholarship'), ('EVENT', 'Event'), ('SOCIETY', 'Society'), ('CLUB', 'Club'), ('OTHER', 'Other')], max_length=100, verbose_name='Notice Type')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark this notice as featured.', verbose_name='Featured')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the notice was published.', verbose_name='Published Date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='APPROVED', help_text='Current approval status of the notice.', max_length=10, verbose_name='Approval Status')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('shares', models.PositiveIntegerField(default=0, verbose_name='shares')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('file', models.FileField(help_text='Upload an image, video, or document.', max_length=255, upload_to=src.notice.utils.notice_media_upload_path, verbose_name='Media File')),
                ('caption', models.CharField(blank=True, help_text='Caption for particular image, document or video.', max_length=255, verbose_name='Caption')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document')], help_text='Type of the uploaded media.', max_length=10, verbose_name='Media Type')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('notice', models.ForeignKey(help_text='The notice this media is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='notice.notice')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('name', models.CharField(default='General', max_length=100, verbose_name='Category Name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.ForeignKey(help_text='Category to which this notice belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_notices', to='notice.noticecategory', verbose_name='Notice Category'),
        ),
        migrations.AddField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='department',
            field=models.ForeignKey(help_text='Department associated with this notice.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['category'], name='notice_noti_categor_67231f_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['department'], name='notice_noti_departm_fd174d_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['slug'], name='notice_noti_slug_7db744_idx'),
        ),
    ]
