# Generated by Django 4.2.2 on 2025-07-15 03:54

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import src.notice.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notice_type', models.CharField(choices=[('Department', 'Department'), ('Administration', 'Administration'), ('Admission', 'Admission'), ('Exam', 'Examination'), ('Scholarship', 'Scholarship'), ('Event', 'Event'), ('Society', 'Society'), ('Club', 'Club'), ('Other', 'Other')], max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Notice Types',
                'ordering': ['notice_type'],
            },
        ),
        migrations.CreateModel(
            name='NoticeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(default='General', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('notice_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_type_set', to='notice.noticetype')),
            ],
            options={
                'verbose_name_plural': 'Notice Categories',
                'ordering': ['notice_type', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, max_length=250, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('download_file', models.FileField(blank=True, null=True, upload_to=src.notice.models.update_filename, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('is_featured', models.BooleanField(default=False)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('notice_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_category_set', to='notice.noticecategory')),
            ],
            options={
                'verbose_name_plural': 'Notices',
                'ordering': ['-published_date'],
            },
        ),
    ]
