# Generated by Django 4.2.2 on 2025-07-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='notice_type',
        ),
    ]
