# Generated by Django 4.2.2 on 2025-11-14 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_alter_departmentdownload_options_and_more'),
        ('notice', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department associated with this notice.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department', verbose_name='Department'),
        ),
    ]
