# Generated by Django 4.2.2 on 2025-11-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0005_alter_notice_is_approved_by_campus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Optional image representing the notice.",
                null=True,
                upload_to="notice/thumbnails",
                verbose_name="Thumbnail",
            ),
        ),
    ]
