# Generated by Django 4.2.2 on 2025-11-20 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_merge_20251119_1437'),
        ('notice', '0006_alter_notice_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='campus_section',
            field=models.ForeignKey(blank=True, help_text='Campus section associated with this notice.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.campussection', verbose_name='Campus Section'),
        ),
        migrations.AddField(
            model_name='notice',
            name='campus_unit',
            field=models.ForeignKey(blank=True, help_text='Campus unit associated with this notice.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.campusunit', verbose_name='Campus Unit'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['campus_unit'], name='notice_noti_campus__c0c287_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['campus_section'], name='notice_noti_campus__6e9585_idx'),
        ),
    ]
