# Generated by Django 4.2.2 on 2025-11-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0007_notice_campus_section_notice_campus_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="is_approved_by_campus",
            field=models.BooleanField(
                default=False,
                help_text="dicates whether the campus has approved this notice.",
                verbose_name="Approved by Campus",
            ),
        ),
    ]
