# Generated by Django 4.2.2 on 2025-11-14 12:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0008_alter_departmentdownload_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the project",
                        max_length=300,
                        verbose_name="Project Title",
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Detailed description of the project",
                        verbose_name="Project Description",
                    ),
                ),
                (
                    "abstract",
                    models.TextField(
                        blank=True,
                        help_text="Brief abstract of the project",
                        verbose_name="Abstract",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("final_year", "Final Year Project"),
                            ("minor", "Minor Project"),
                            ("major", "Major Project"),
                            ("research", "Research Project"),
                            ("other", "Other"),
                        ],
                        default="final_year",
                        max_length=20,
                        verbose_name="Project Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "supervisor_name",
                    models.CharField(
                        help_text="Name of the project supervisor",
                        max_length=200,
                        verbose_name="Supervisor Name",
                    ),
                ),
                (
                    "supervisor_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email of the project supervisor",
                        max_length=254,
                        verbose_name="Supervisor Email",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        help_text="Academic year (e.g., 2024-2025)",
                        max_length=20,
                        verbose_name="Academic Year",
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        help_text="GitHub repository URL",
                        verbose_name="GitHub URL",
                    ),
                ),
                (
                    "demo_url",
                    models.URLField(
                        blank=True, help_text="Live demo URL", verbose_name="Demo URL"
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        help_text="Upload project report PDF",
                        upload_to="projects/reports/",
                        verbose_name="Project Report",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Project thumbnail image",
                        upload_to="projects/thumbnails/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "technologies_used",
                    models.TextField(
                        blank=True,
                        help_text="List of technologies/tools used (comma separated)",
                        verbose_name="Technologies Used",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as featured project",
                        verbose_name="Featured Project",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Make project visible to public",
                        verbose_name="Published",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Views Count"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="department.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tag name",
                        max_length=100,
                        unique=True,
                        verbose_name="Tag Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL slug for the tag",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Hex color code for the tag",
                        max_length=7,
                        verbose_name="Color",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Tag",
                "verbose_name_plural": "Project Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTagAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_assignments",
                        to="project.project",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_assignments",
                        to="project.projecttag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Tag Assignment",
                "verbose_name_plural": "Project Tag Assignments",
                "unique_together": {("project", "tag")},
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Full name of the student",
                        max_length=200,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "roll_number",
                    models.CharField(
                        help_text="Student's roll number",
                        max_length=50,
                        verbose_name="Roll Number",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Student's email address",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Student's phone number",
                        max_length=20,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        default="Team Member",
                        help_text="Role in the project (e.g., Team Leader, Developer, etc.)",
                        max_length=100,
                        verbose_name="Role",
                    ),
                ),
                (
                    "linkedin_url",
                    models.URLField(
                        blank=True,
                        help_text="LinkedIn profile URL",
                        verbose_name="LinkedIn URL",
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True,
                        help_text="GitHub profile URL",
                        verbose_name="GitHub URL",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Student's department",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="department.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="project.project",
                        verbose_name="Project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Member",
                "verbose_name_plural": "Project Members",
                "ordering": ["id"],
                "unique_together": {("project", "roll_number")},
            },
        ),
    ]
