from src.base.constants import BaseEnum


class Genders(BaseEnum):
    MALE = "MALE"
    FEMALE = "FEMALE"
    OTHER = "OTHER"
    RATHER_NOT_TO_SAY = "RATHER_NOT_TO_SAY"


SYSTEM_USER_ROLE = "SYSTEM-USER"
PUBLIC_USER_ROLE = "PUBLIC-USER"
ADMIN_ROLE = "ADMIN"
EMIS_STAFF_ROLE = "EMIS-STAFF"
DEPARTMENT_ADMIN_ROLE = "DEPARTMENT-ADMIN"
CLUB_ROLE = "CLUB"
UNION_ROLE = "UNION"
CAMPUS_UNIT_ROLE = "CAMPUS-UNIT"
CAMPUS_SECTION_ROLE = "CAMPUS-SECTION"
