# Generated by Django 4.2.2 on 2025-11-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_remove_appointment_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentslot",
            name="office_identifier",
            field=models.CharField(
                blank=True,
                help_text='Optional identifier to distinguish between officials with same designation (e.g., "Office A", "Block 1", etc.)',
                max_length=50,
                verbose_name="Office Identifier",
            ),
        ),
    ]
