# Generated by Django 4.2.2 on 2025-11-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_appointmentslot_office_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentcategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("CAMPUS_CHIEF", "Campus Chief"),
                    (
                        "ASSISTANT_CAMPUS_CHIEF_ADMIN",
                        "Assistant Campus Chief (Administration)",
                    ),
                    (
                        "ASSISTANT_CAMPUS_CHIEF_ACADEMIC",
                        "Assistant Campus Chief (Academic)",
                    ),
                    (
                        "ASSISTANT_CAMPUS_CHIEF_PLANNING",
                        "Assistant Campus Chief (Planning & Resource)",
                    ),
                    ("DEPARTMENT_HEAD", "Department Head"),
                ],
                max_length=100,
                unique=True,
                verbose_name="Category Name",
            ),
        ),
    ]
