# Generated by Django 4.2.2 on 2025-11-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0005_make_categories_dynamic"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_slot_datetime_active",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="slot",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="appointment_time",
            field=models.CharField(
                help_text='Preferred appointment time (e.g., "2:00 PM", "14:30", "Morning")',
                max_length=100,
                verbose_name="Preferred Time",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["PENDING", "CONFIRMED"])),
                fields=("category", "appointment_date", "appointment_time"),
                name="unique_category_datetime_active",
            ),
        ),
    ]
