# Generated by Django 4.2.2 on 2025-11-29 14:06

from django.db import migrations, models
from django.utils import timezone
from datetime import datetime, time


def migrate_appointment_datetime_data(apps, schema_editor):
    """
    Migrate existing appointment_date and appointment_time to appointment_datetime
    """
    Appointment = apps.get_model('appointments', 'Appointment')
    
    for appointment in Appointment.objects.all():
        if appointment.appointment_date and appointment.appointment_time:
            # Try to parse the time string and combine with date
            try:
                # Default time if parsing fails
                default_time = time(9, 0)  # 9:00 AM
                
                # Try to parse common time formats
                time_str = appointment.appointment_time.strip().lower()
                
                # Simple parsing for common formats
                if 'morning' in time_str:
                    parsed_time = time(9, 0)
                elif 'afternoon' in time_str:
                    parsed_time = time(14, 0)
                elif 'evening' in time_str:
                    parsed_time = time(17, 0)
                elif ':' in time_str:
                    # Try to parse "HH:MM" or "H:MM" format
                    try:
                        # Remove AM/PM and extra spaces
                        clean_time = time_str.replace('am', '').replace('pm', '').strip()
                        if 'pm' in time_str and not clean_time.startswith('12'):
                            # Add 12 hours for PM (except 12 PM)
                            hour, minute = map(int, clean_time.split(':'))
                            hour += 12
                            parsed_time = time(hour, minute)
                        else:
                            hour, minute = map(int, clean_time.split(':'))
                            parsed_time = time(hour, minute)
                    except:
                        parsed_time = default_time
                else:
                    parsed_time = default_time
                
                # Combine date and time
                appointment_datetime = datetime.combine(
                    appointment.appointment_date, 
                    parsed_time
                )
                
                # Make timezone aware
                appointment.appointment_datetime = timezone.make_aware(appointment_datetime)
                appointment.save()
                
            except Exception as e:
                # Fallback to date + 9 AM if anything goes wrong
                appointment_datetime = datetime.combine(
                    appointment.appointment_date,
                    time(9, 0)
                )
                appointment.appointment_datetime = timezone.make_aware(appointment_datetime)
                appointment.save()


def reverse_migrate_appointment_datetime_data(apps, schema_editor):
    """
    Reverse migration - extract date and time from datetime field
    """
    Appointment = apps.get_model('appointments', 'Appointment')
    
    for appointment in Appointment.objects.all():
        if appointment.appointment_datetime:
            appointment.appointment_date = appointment.appointment_datetime.date()
            appointment.appointment_time = appointment.appointment_datetime.strftime('%I:%M %p')
            appointment.save()


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0006_remove_slot_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="appointment_datetime",
            field=models.DateTimeField(
                blank=True,
                help_text="Requested appointment date and time",
                null=True,
                verbose_name="Appointment Date & Time",
            ),
        ),
        migrations.RunPython(
            migrate_appointment_datetime_data,
            reverse_migrate_appointment_datetime_data,
        ),
    ]
