# Generated by Django 4.2.2 on 2025-11-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0008_populate_and_require_datetime"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="appointment",
            name="unique_category_datetime_active",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="appointment_date",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="appointment_time",
        ),
    ]
