# Generated by Django 4.2.2 on 2025-11-21 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('requester_email', models.EmailField(max_length=254, verbose_name='requester email')),
                ('requester_name', models.CharField(max_length=255, verbose_name='requester name')),
                ('requester_phone', models.CharField(blank=True, max_length=15, verbose_name='requester phone')),
                ('requester_department', models.CharField(blank=True, max_length=255, verbose_name='department/affiliation')),
                ('request_type', models.CharField(choices=[('NEW_EMAIL', 'New Email Account'), ('PASSWORD_RESET', 'Password Reset'), ('QUOTA_INCREASE', 'Quota Increase'), ('FORWARDING', 'Email Forwarding'), ('ALIAS', 'Email Alias'), ('OTHER', 'Other')], max_length=20, verbose_name='request type')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('message', models.TextField(verbose_name='message')),
                ('requested_email', models.EmailField(blank=True, help_text='Email address being requested (for new account requests)', max_length=254, verbose_name='requested email')),
                ('requires_application', models.BooleanField(default=False, help_text='Set to True if requester has 10+ requests', verbose_name='requires application')),
                ('application_document', models.FileField(blank=True, null=True, upload_to='email_requests/applications/%Y/%m/', verbose_name='application document')),
                ('request_number', models.PositiveIntegerField(default=1, help_text='Number of requests from this user/email', verbose_name='request number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20, verbose_name='status')),
                ('response_message', models.TextField(blank=True, verbose_name='response message')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('created_email', models.EmailField(blank=True, help_text='The actual email address that was created', max_length=254, verbose_name='created email')),
                ('email_password', models.CharField(blank=True, help_text='Temporary password (if applicable)', max_length=255, verbose_name='temporary password')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_email_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Registered user (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email request',
                'verbose_name_plural': 'email requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='application_user_id_fbca77_idx'), models.Index(fields=['requester_email', 'status'], name='application_request_c83227_idx'), models.Index(fields=['status', '-created_at'], name='application_status_57aba4_idx')],
            },
        ),
    ]
