# Generated by Django 4.2.2 on 2025-11-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_add_contact_type_and_department_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="phone_number",
            field=models.CharField(
                help_text="Phone number for this contact",
                max_length=20,
                verbose_name="Phone Number",
            ),
        ),
    ]
