# Generated by Django 4.1.4 on 2023-06-20 12:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TCIOE', editable=False, max_length=100, unique=True)),
                ('slider_image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slider_image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slider_image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slider_image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField()),
                ('phone_one', models.CharField(max_length=20)),
                ('phone_two', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_three', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMemberSocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='doece-facebook', max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube'), ('GitHub', 'GitHub'), ('Website', 'Website')], default='Facebook', max_length=100, unique=True)),
                ('link', models.URLField()),
                ('staff_member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members_social_media', to='department.staffmember')),
            ],
            options={
                'abstract': False,
                'unique_together': {('type', 'link')},
            },
        ),
        migrations.CreateModel(
            name='SocietySocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='doece-facebook', max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube'), ('GitHub', 'GitHub'), ('Website', 'Website')], default='Facebook', max_length=100, unique=True)),
                ('link', models.URLField()),
                ('society_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_social_media', to='department.society')),
            ],
            options={
                'abstract': False,
                'unique_together': {('type', 'link')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentSocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='doece-facebook', max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube'), ('GitHub', 'GitHub'), ('Website', 'Website')], default='Facebook', max_length=100, unique=True)),
                ('link', models.URLField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_social_media', to='department.department')),
            ],
            options={
                'abstract': False,
                'unique_together': {('type', 'link')},
            },
        ),
    ]
