# Generated by Django 4.2.2 on 2023-06-20 05:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TCIOE', editable=False, max_length=100, unique=True)),
                ('slider_image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slider_image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slider_image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('slider_image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField()),
                ('phone_one', models.CharField(max_length=20)),
                ('phone_two', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_three', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='doece-facebook', max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn'), ('YouTube', 'YouTube'), ('GitHub', 'GitHub'), ('Website', 'Website')], default='Facebook', max_length=100, unique=True)),
                ('link', models.URLField()),
            ],
            options={
                'unique_together': {('type', 'link')},
            },
        ),
    ]
