# Generated by Django 4.2.2 on 2023-06-21 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='name',
            field=models.CharField(choices=[('TCIOE_HOME', 'Thapathali Campus'), ('TCIOE_ADMINISTRATION', 'Campus Administration'), ('TCIOE_LIBRARY', 'Campus Library')], default='TCIOE', max_length=100, unique=True),
        ),
    ]
