# Generated by Django 4.2.2 on 2025-11-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0009_departmentevent_location_and_more"),
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department associated with this article (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_articles",
                to="department.department",
                verbose_name="Department",
            ),
        ),
    ]
