# Generated by Django 4.2.2 on 2025-11-14 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0012_delete_staffmember"),
        ("journal", "0002_article_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="academic_program",
            field=models.ForeignKey(
                blank=True,
                help_text="Academic program associated with this article (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journal_articles_by_program",
                to="department.academicprogram",
                verbose_name="Academic Program",
            ),
        ),
    ]
