# Generated by Django 4.2.2 on 2025-07-15 03:54

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("I/I", "I/I"),
                            ("I/II", "I/II"),
                            ("II/I", "II/I"),
                            ("II/II", "II/II"),
                            ("III/I", "III/I"),
                            ("III/II", "III/II"),
                            ("IV/I", "IV/I"),
                            ("IV/II", "IV/II"),
                            ("V/I", "V/I"),
                            ("V/II", "V/II"),
                        ],
                        max_length=200,
                    ),
                ),
                ("routine_png", models.ImageField(upload_to="media/routine/")),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20)),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("I/I", "I/I"),
                            ("I/II", "I/II"),
                            ("II/I", "II/I"),
                            ("II/II", "II/II"),
                            ("III/I", "III/I"),
                            ("III/II", "III/II"),
                            ("IV/I", "IV/I"),
                            ("IV/II", "IV/II"),
                            ("V/I", "V/I"),
                            ("V/II", "V/II"),
                        ],
                        max_length=200,
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        choices=[
                            (
                                "Bachelor of Electronics, Information and Communication Engineering",
                                "BEI",
                            ),
                            ("Bachelor of Computer Engineering", "BCT"),
                            ("Bachelor of Civil Engineering", "BCE"),
                            ("Bachelor of Industrial Engineering", "BIE"),
                            ("Bachelor of AutoMobile Engineering", "BAM"),
                            ("Bachelor of Mechanical Engineering", "BME"),
                            ("Bachelor of Architecture Engineering", "B.Arch"),
                        ],
                        max_length=200,
                    ),
                ),
                ("topics_covered", ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("message", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
