# Generated by Django 4.2.2 on 2025-11-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_alter_departmentdownload_options_and_more'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='academic_program',
            field=models.ForeignKey(blank=True, help_text='Optional reference to a department-level academic program.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='department.academicprogram'),
        ),
    ]
