from src.base.constants import BaseEnum

DEPARTMENT_THUMBNAIL_PATH = "department/thumbnails"
DEPARTMENT_PROGRAM_THUMBNAIL_PATH = "department/programs"
DEPARTMENT_STAFF_PHOTO_PATH = "department/staffs"
DEPARTMENT_DOWNLOADS_FILE_PATH = "department/downloads"
DEPARTMENT_EVENT_FILE_PATH = "department/events"


class DepartmentDesignationChoices(BaseEnum):
    # Department Leadership
    HOD = "HOD"
    DHOD = "DHOD"

    # Academic Hierarchy
    PROFESSOR = "PROFESSOR"
    ASSOCIATE_PROFESSOR = "ASSOCIATE_PROFESSOR"
    ASSISTANT_PROFESSOR = "ASSISTANT_PROFESSOR"
    READER = "READER"
    LECTURER = "LECTURER"
    SENIOR_INSTRUCTOR = "SENIOR_INSTRUCTOR"
    INSTRUCTOR = "INSTRUCTOR"
    TEACHING_ASSISTANCE = "TEACHING_ASSISTANCE"

    # Department Administration
    SECTION_OFFICER = "SECTION_OFFICER"
    CHIEF_OFFICE_ASSISTANT = "CHIEF_OFFICE_ASSISTANT"
    HEAD_TECHNICAL_ASSISTANT = "HEAD_TECHNICAL_ASSISTANT"
    TECHNICAL_ASSISTANT = "TECHNICAL_ASSISTANT"
    LABORATORY_ASSISTANT = "LABORATORY_ASSISTANT"
    OFFICE_ASSISTANT = "OFFICE_ASSISTANT"
    COMPUTER_OPERATOR = "COMPUTER_OPERATOR"

    # Support Staff
    DRIVER = "DRIVER"
    SECURITY_GUARD = "SECURITY_GUARD"
    OFFICE_HELPER = "OFFICE_HELPER"


class DepartmentEventTypes(BaseEnum):
    CULTURAL = "CULTURAL"
    TECHNICAL = "TECHNICAL"
    MUSICAL = "MUSICAL"
    SPORTS = "SPORTS"
    OTHER = "OTHER"
