# Generated by Django 4.2.2 on 2023-06-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_alter_notice_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
