# Generated by Django 4.2.2 on 2025-07-16 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Represents unique uuid.', unique=True, verbose_name='uuid')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting instances.', verbose_name='active')),
                ('is_archived', models.BooleanField(default=False, help_text='Designates whether this object should be treated as delected. Unselect this instead of deleting instances.', verbose_name='archived')),
                ('email_type', models.CharField(choices=[('INFO', 'Info'), ('SUPPORT', 'Support')], default='INFO', help_text='Type of email (e.g. sales, info)', max_length=20, unique=True)),
                ('email_host', models.CharField(default='smtp.gmail.com', help_text='SMTP server address', max_length=255)),
                ('email_use_tls', models.BooleanField(default=True, help_text='Use TLS for the email connection')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Use SSL for the email connection')),
                ('email_port', models.PositiveIntegerField(default=587, help_text='Port for the email server')),
                ('email_host_user', models.EmailField(help_text='Email host user', max_length=254)),
                ('email_host_password', models.CharField(help_text='Email host password', max_length=255)),
                ('default_from_email', models.EmailField(help_text="Default 'from' email address", max_length=254)),
                ('server_mail', models.EmailField(blank=True, help_text='Email address for server errors', max_length=254)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configurations',
            },
        ),
    ]
