# Generated by Django 4.2.2 on 2025-07-19 04:48

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalSessionBS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Represents unique uuid.",
                        unique=True,
                        verbose_name="uuid",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "session_full",
                    models.CharField(
                        help_text="E.g. 2079/2080",
                        max_length=9,
                        unique=True,
                        verbose_name="Full Session",
                    ),
                ),
                (
                    "session_short",
                    models.CharField(
                        help_text="E.g. 079/80",
                        max_length=5,
                        unique=True,
                        verbose_name="Short Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Session (BS)",
                "verbose_name_plural": "Fiscal Sessions (BS)",
            },
        ),
    ]
