# Generated by Django 4.2.2 on 2025-07-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_fiscalsessionbs_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailconfig",
            name="email_type",
            field=models.CharField(
                choices=[("INFO", "Info"), ("HELP", "Help"), ("NOREPLY", "Noreply")],
                default="INFO",
                help_text="Type of email (e.g. sales, info)",
                max_length=20,
                unique=True,
            ),
        ),
    ]
