# Generated by Django 4.2.2 on 2025-11-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_emailconfig_email_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When these statistics were last calculated",
                    ),
                ),
                (
                    "total_users",
                    models.IntegerField(default=0, help_text="Total number of users"),
                ),
                (
                    "active_users",
                    models.IntegerField(
                        default=0, help_text="Users active in last 30 days"
                    ),
                ),
                (
                    "new_users_this_month",
                    models.IntegerField(
                        default=0, help_text="New users registered this month"
                    ),
                ),
                (
                    "users_by_role",
                    models.JSONField(
                        blank=True, default=dict, help_text="User count grouped by role"
                    ),
                ),
                (
                    "total_departments",
                    models.IntegerField(
                        default=0, help_text="Total number of departments"
                    ),
                ),
                (
                    "active_departments",
                    models.IntegerField(default=0, help_text="Active departments"),
                ),
                (
                    "total_notices",
                    models.IntegerField(default=0, help_text="Total number of notices"),
                ),
                (
                    "active_notices",
                    models.IntegerField(default=0, help_text="Published notices"),
                ),
                (
                    "draft_notices",
                    models.IntegerField(default=0, help_text="Draft notices"),
                ),
                (
                    "featured_notices",
                    models.IntegerField(default=0, help_text="Featured notices"),
                ),
                (
                    "notices_by_category",
                    models.JSONField(
                        blank=True, default=dict, help_text="Notice count by category"
                    ),
                ),
                (
                    "recent_notices_count",
                    models.IntegerField(
                        default=0, help_text="Notices published in last 7 days"
                    ),
                ),
                (
                    "total_projects",
                    models.IntegerField(
                        default=0, help_text="Total number of projects"
                    ),
                ),
                (
                    "projects_by_status",
                    models.JSONField(
                        blank=True, default=dict, help_text="Projects grouped by status"
                    ),
                ),
                (
                    "projects_by_type",
                    models.JSONField(
                        blank=True, default=dict, help_text="Projects grouped by type"
                    ),
                ),
                (
                    "projects_by_department",
                    models.JSONField(
                        blank=True, default=dict, help_text="Projects per department"
                    ),
                ),
                (
                    "completed_projects_this_year",
                    models.IntegerField(
                        default=0, help_text="Projects completed this year"
                    ),
                ),
                (
                    "total_research",
                    models.IntegerField(default=0, help_text="Total research papers"),
                ),
                (
                    "research_by_status",
                    models.JSONField(
                        blank=True, default=dict, help_text="Research grouped by status"
                    ),
                ),
                (
                    "research_by_type",
                    models.JSONField(
                        blank=True, default=dict, help_text="Research grouped by type"
                    ),
                ),
                (
                    "published_research_this_year",
                    models.IntegerField(
                        default=0, help_text="Research published this year"
                    ),
                ),
                (
                    "total_articles",
                    models.IntegerField(default=0, help_text="Total journal articles"),
                ),
                (
                    "total_authors",
                    models.IntegerField(default=0, help_text="Total authors"),
                ),
                (
                    "total_board_members",
                    models.IntegerField(default=0, help_text="Total board members"),
                ),
                (
                    "total_subjects",
                    models.IntegerField(default=0, help_text="Total subjects"),
                ),
                (
                    "total_routines",
                    models.IntegerField(default=0, help_text="Total class routines"),
                ),
                (
                    "total_suggestions",
                    models.IntegerField(
                        default=0, help_text="Total suggestions received"
                    ),
                ),
                (
                    "total_contact_submissions",
                    models.IntegerField(
                        default=0, help_text="Total contact form submissions"
                    ),
                ),
                (
                    "pending_inquiries",
                    models.IntegerField(default=0, help_text="Pending inquiries"),
                ),
                (
                    "notices_trend",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Notice count over last 6 months [{month: 'Jan', count: 10}, ...]",
                    ),
                ),
                (
                    "users_growth",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="User registration trend over last 6 months",
                    ),
                ),
                (
                    "research_publications_trend",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Research publications over last 12 months",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Statistics",
                "verbose_name_plural": "Dashboard Statistics",
                "ordering": ["-calculated_at"],
            },
        ),
    ]
