# Generated by Django 4.2.2 on 2025-07-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_emailconfig_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalsessionbs',
            name='session_short',
            field=models.CharField(help_text='E.g. 79/80', max_length=5, unique=True, verbose_name='Short Session'),
        ),
    ]
