# Generated by Django 4.2.2 on 2025-11-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_dashboardstats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboardstats",
            name="pending_inquiries",
        ),
        migrations.RemoveField(
            model_name="dashboardstats",
            name="total_contact_submissions",
        ),
        migrations.AddField(
            model_name="dashboardstats",
            name="pending_feedback",
            field=models.IntegerField(default=0, help_text="Pending feedback"),
        ),
        migrations.AddField(
            model_name="dashboardstats",
            name="total_feedback_submissions",
            field=models.IntegerField(
                default=0, help_text="Total feedback submissions"
            ),
        ),
    ]
