# Generated by Django 4.2.2 on 2025-11-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_dashboardstats_pending_inquiries_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardstats",
            name="events_trend",
            field=models.JSONField(
                blank=True, default=list, help_text="Events created over last 6 months"
            ),
        ),
        migrations.AddField(
            model_name="dashboardstats",
            name="pending_events",
            field=models.IntegerField(
                default=0, help_text="Upcoming events not yet started"
            ),
        ),
        migrations.AddField(
            model_name="dashboardstats",
            name="pending_notices",
            field=models.IntegerField(
                default=0, help_text="Draft notices pending publication"
            ),
        ),
        migrations.AddField(
            model_name="dashboardstats",
            name="pending_projects",
            field=models.IntegerField(
                default=0, help_text="Ongoing/incomplete projects"
            ),
        ),
        migrations.AddField(
            model_name="dashboardstats",
            name="pending_research",
            field=models.IntegerField(
                default=0, help_text="Research papers pending review/publication"
            ),
        ),
        migrations.AddField(
            model_name="dashboardstats",
            name="projects_trend",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Projects created over last 6 months",
            ),
        ),
    ]
