# Generated by Django 4.2.2 on 2025-11-29 08:14

from django.db import migrations


def remove_enquiry_tables(apps, schema_editor):
    """Remove enquiry app tables and migration records"""
    db_alias = schema_editor.connection.alias
    
    # Remove the table if it exists
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS enquiry_meetingenquiry")
        print("Removed enquiry_meetingenquiry table")
        
        # Remove migration records for enquiry app
        cursor.execute("DELETE FROM django_migrations WHERE app = 'enquiry'")
        print("Removed enquiry migration records")


def reverse_remove_enquiry_tables(apps, schema_editor):
    """Reverse operation - not implemented as this is a cleanup migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_dashboardstats_events_trend_and_more"),
    ]

    operations = [
        migrations.RunPython(
            remove_enquiry_tables,
            reverse_remove_enquiry_tables,
        ),
    ]
