from src.base.constants import BaseEnum

CAMPUS_FILE_PATH = "website/files"
CAMPUS_KEY_OFFICIAL_FILE_PATH = "website/key-officials"
ACADEMIC_CALENDER_FILE_PATH = "website/calenders"
CAMPUS_REPORT_FILE_PATH = "website/reports"
CAMPUS_DOWNLOADS_FILE_PATH = "website/downloads"
CAMPUS_EVENT_FILE_PATH = "website/events"

CAMPUS_UNION_FILE_PATH = "website/unions"
CAMPUS_UNION_MEMBER_FILE_PATH = "website/unions/members"

STUDENT_CLUB_FILE_PATH = "website/clubs"
STUDENT_CLUB_MEMBER_FILE_PATH = "website/clubs/members"
STUDENT_CLUB_EVENT_FILE_PATH = "website/clubs"


class ReportTypes(BaseEnum):
    SELF_STUDY = "SELF_STUDY"
    ANNUAL = "ANNUAL"
    OTHER = "OTHER"


class CampusEventTypes(BaseEnum):
    CULTURAL = "CULTURAL"
    TECHNICAL = "TECHNICAL"
    MUSICAL = "MUSICAL"
    SPORTS = "SPORTS"
    OTHER = "OTHER"


class CampusDesignationChoices(BaseEnum):
    # Campus Leadership
    CAMPUS_CHIEF = "CAMPUS_CHIEF"
    ASSIST_CAMPUS_CHIEF_ADMIN = "ASSIST_CAMPUS_CHIEF_ADMIN"
    ASSIST_CAMPUS_CHIEF_ACADEMIC = "ASSIST_CAMPUS_CHIEF_ACADEMIC"
    ASSIST_CAMPUS_CHIEF_PLANNING = "ASSIST_CAMPUS_CHIEF_PLANNING"

    # MSC Program Coordination
    MSC_COORD_INFORMATION = "MSC_COORD_INFORMATION"
    MSC_COORD_EARTHQUAKE = "MSC_COORD_EARTHQUAKE"
    MSC_COORD_DESIGN = "MSC_COORD_DESIGN"

    # Campus Department Heads
    EMIS_HEAD = "EMIS_HEAD"
    RESEARCH_HEAD = "RESEARCH_HEAD"
    CONSULTANCY_HEAD = "CONSULTANCY_HEAD"
    EXAMS_ACADEMIC_HEAD = "EXAMS_ACADEMIC_HEAD"
    LIBRARY_HEAD = "LIBRARY_HEAD"
    FINANCE_HEAD = "FINANCE_HEAD"
    PERSONNEL_HEAD = "PERSONNEL_HEAD"
    PLANNING_HEAD = "PLANNING_HEAD"
    PROCUREMENT_HEAD = "PROCUREMENT_HEAD"
    SECURITY_HEAD = "SECURITY_HEAD"
    IQAC_HEAD = "IQAC_HEAD"
    ADMINISTRATION_HEAD = "ADMINISTRATION_HEAD"
    FACILITIES_HEAD = "FACILITIES_HEAD"

    # Campus Officers
    DEPUTY_FINANCE_CONTROLLER = "DEPUTY_FINANCE_CONTROLLER"
    LIBRARIAN = "LIBRARIAN"
    ACCOUNT_OFFICER = "ACCOUNT_OFFICER"
