from src.base.constants import BaseEnum

CAMPUS_FILE_PATH = "website/files"
CAMPUS_KEY_OFFICIAL_FILE_PATH = "website/key-officials"
ACADEMIC_CALENDER_FILE_PATH = "website/calenders"
CAMPUS_REPORT_FILE_PATH = "website/reports"
CAMPUS_DOWNLOADS_FILE_PATH = "website/downloads"
CAMPUS_EVENT_FILE_PATH = "website/events"

CAMPUS_UNION_FILE_PATH = "website/unions"
CAMPUS_UNION_MEMBER_FILE_PATH = "website/unions/members"

STUDENT_CLUB_FILE_PATH = "website/clubs"
STUDENT_CLUB_MEMBER_FILE_PATH = "website/clubs/members"
STUDENT_CLUB_EVENT_FILE_PATH = "website/clubs"
CAMPUS_SECTION_FILE_PATH = "website/sections"
CAMPUS_SECTION_MEMBER_FILE_PATH = "website/sections/members"
CAMPUS_UNIT_FILE_PATH = "website/units"
CAMPUS_UNIT_MEMBER_FILE_PATH = "website/units/members"


class ReportTypes(BaseEnum):
    SELF_STUDY = "SELF_STUDY"
    ANNUAL = "ANNUAL"
    OTHER = "OTHER"


class CampusEventTypes(BaseEnum):
    CULTURAL = "CULTURAL"
    TECHNICAL = "TECHNICAL"
    MUSICAL = "MUSICAL"
    SPORTS = "SPORTS"
    OTHER = "OTHER"


class CampusDesignationChoices(BaseEnum):
    # Campus Leadership
    CAMPUS_CHIEF = "CAMPUS_CHIEF"
    ASSIST_CAMPUS_CHIEF_ADMIN = "ASSIST_CAMPUS_CHIEF_ADMIN"
    ASSIST_CAMPUS_CHIEF_ACADEMIC = "ASSIST_CAMPUS_CHIEF_ACADEMIC"
    ASSIST_CAMPUS_CHIEF_PLANNING = "ASSIST_CAMPUS_CHIEF_PLANNING"

    # MSC Program Coordination
    MSC_COORD_INFORMATION = "MSC_COORD_INFORMATION"
    MSC_COORD_EARTHQUAKE = "MSC_COORD_EARTHQUAKE"
    MSC_COORD_DESIGN = "MSC_COORD_DESIGN"
    MSC_COORD_MSEQE = "MSC_COORD_MSEQE"
    MSC_COORD_MSIS = "MSC_COORD_MSIS"
    MSC_COORD_MSEDM = "MSC_COORD_MSEDM"

    # Campus Department Heads
    HEAD_OF_INDUSTRIAL_DEPARTMENT = "HEAD_OF_INDUSTRIAL_DEPARTMENT"
    HEAD_OF_ARCHITECTURE_DEPARTMENT = "HEAD_OF_ARCHITECTURE_DEPARTMENT"
    HEAD_OF_APPLIED_SCIENCE_DEPARTMENT = "HEAD_OF_APPLIED_SCIENCE_DEPARTMENT"
    HEAD_OF_AUTOMOBILE_AND_MECHANICAL_DEPARTMENT = (
        "HEAD_OF_AUTOMOBILE_AND_MECHANICAL_DEPARTMENT"
    )
    HEAD_OF_ELECTRONICS_AND_COMPUTER_DEPARTMENT = (
        "HEAD_OF_ELECTRONICS_AND_COMPUTER_DEPARTMENT"
    )
    EMIS_HEAD = "EMIS_HEAD"
    RESEARCH_HEAD = "RESEARCH_HEAD"
    CONSULTANCY_HEAD = "CONSULTANCY_HEAD"
    EXAMS_ACADEMIC_HEAD = "EXAMS_ACADEMIC_HEAD"
    LIBRARY_HEAD = "LIBRARY_HEAD"
    FINANCE_HEAD = "FINANCE_HEAD"
    PERSONNEL_HEAD = "PERSONNEL_HEAD"
    PLANNING_HEAD = "PLANNING_HEAD"
    PROCUREMENT_HEAD = "PROCUREMENT_HEAD"
    SECURITY_HEAD = "SECURITY_HEAD"
    IQAC_HEAD = "IQAC_HEAD"
    ADMINISTRATION_HEAD = "ADMINISTRATION_HEAD"
    FACILITIES_HEAD = "FACILITIES_HEAD"
    HEAD_OF_MATERIAL_TESTING_LAB = "HEAD_OF_MATERIAL_TESTING_LAB"
    HEAD_OF_STORE_SECTION = "HEAD_OF_STORE_SECTION"
    HEAD_OF_FINANCE_ADMINISTRATION_SECTION = "HEAD_OF_FINANCE_ADMINISTRATION_SECTION"
    HEAD_OF_EMIS_UNIT = "HEAD_OF_EMIS_UNIT"
    HEAD_OF_SAT = "HEAD_OF_SAT"

    # Campus Officers
    DEPUTY_FINANCE_CONTROLLER = "DEPUTY_FINANCE_CONTROLLER"
    LIBRARIAN = "LIBRARIAN"
    ACCOUNT_OFFICER = "ACCOUNT_OFFICER"
