# Generated by Django 4.2.2 on 2023-06-21 16:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('DOECE', 'Department of Electronics and Communication Engineering'), ('DOCE', 'Department of Civil and Industrial Engineering'), ('DOAME', 'Department of AutoMobile and Mechanical Engineering'), ('DOARCH', 'Department of Architecture')], default='DOECE', max_length=100, unique=True)),
                ('introduction', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_social_media', to='home.socialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(choices=[('CHIEF', 'Campus Chief'), ('ASSIST_CHIEF', 'Assistant Campus Chief'), ('HOD', 'Head of Department'), ('DHOD', 'Deputy Head of Department'), ('PROF', 'Professor'), ('ASSO_PROF', 'Associate Professor'), ('ASSIST_PROF', 'Assistant Professor'), ('LECT', 'Lecturer'), ('HELPING_STAFF', 'Helping Staff')], max_length=100)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.designation')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_social_media', to='home.socialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('founded_at', models.DateField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_social_media', to='home.socialmedia')),
            ],
        ),
    ]
