# Generated by Django 4.2.2 on 2023-07-20 16:33

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('Department of Electronics and Computer Engineering', 'DOECE'), ('Department of Civil Engineering', 'DOCE'), ('Department of Industrial Engineering', 'DOIE'), ('Department of AutoMobile and Mechanical Engineering', 'DOAME'), ('Department of Architecture', 'DOARCH'), ('Department od Applied Science', 'DOAS'), ('Administration', 'Admninistartion'), ('Library', 'Library')], default='DOECE', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('introduction', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('routine', models.ImageField(blank=True, null=True, upload_to='media/routine/')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='media/profile/')),
                ('is_academic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('designation', models.CharField(choices=[('CHIEF', 'Campus Chief'), ('ASSIST_CAMPUS_CHIEF_ADMIN', 'Assistant Campus Chief Administration'), ('ASSIST_CAMPUS_CHIEF_ACADEMIC', 'Assistant Campus Chief Academic'), ('ASSIST_CAMPUS_CHIEF_PLANNING', 'Assistant Campus Chief Planning and Resource Management'), ('HOD', 'Head of Department'), ('DHOD', 'Deputy Head of Department'), ('MSC_COORD', 'MSc. Coordinator'), ('EMIS_HEAD', 'EMIS Head'), ('RESEARCH_HEAD', 'Research and Development Head'), ('MATERIAL_HEAD', 'Material Testing Head'), ('CONSULTANCY_HEAD', 'Consultancy Head'), ('EXAMS_ACADEMIC_HEAD', 'Examination and Academic Administration Head'), ('LIBRARY_HEAD', 'Library Head'), ('FINANCE_HEAD', 'Finance Administration Head'), ('PERSONNEL_HEAD', 'Personnel Administration Head'), ('GENERAL_HEAD', 'General Administration Head'), ('PLANNING_HEAD', 'Planning Head'), ('PROCUREMENT_HEAD', 'Procurement and Stores Head'), ('SECURITY_HEAD', 'Security and Property Management Head'), ('REPAIR_HEAD', 'Repair and Maintenance Head'), ('IQAC_HEAD', 'IQAC Head'), ('SAT_HEAD', 'SAT Head'), ('ADMINISTRATION_HEAD', 'Administration Head'), ('STORE_HEAD', 'Store Head'), ('ACCOUNT_HEAD', 'Account Head'), ('LECTURER', 'Lecturer'), ('SENIOR_INSTRUCTOR', 'Senior Instructor'), ('TEACHING_ASSISTANCE', 'Teaching Assistance'), ('INSTRUCTOR', 'Instructor'), ('READER', 'Reader'), ('PROFESSOR', 'Professor'), ('ASSOCIATE_PROFESSOR', 'Associate Professor'), ('DEPUTY_INSTRUCTOR', 'Deputy Instructor'), ('ASSISTANT_INSTRUCTOR', 'Assistant Instructor'), ('ASSISTANT_PROFESSOR', 'Assistant Professor'), ('ASSISTANT_FINANCE_CONTROLLER', 'Assistant Finance Controller'), ('DEPUTY_ADM_OFFICER', 'Deputy ADM Officer'), ('DEPUTY_FINANCE_CONTROLLER', 'Deputy Finance Controller'), ('SECTION_OFFICER', 'Section Officer'), ('CHIEF_OFFICE_ASSISTANT', 'Chief Office Assistant'), ('HEAD_ACCOUNT_ASSISTANCE', 'Head Account Assistance'), ('LIBRARY_ASSISTANT', 'Library Assistant'), ('OFFICE_ASSISTANT', 'Office Assistant'), ('TECHNICAL_ASSISTANT', 'Technical Assistant'), ('DRIVER', 'Driver'), ('SENIOR_OFFICE_HELPER', 'Senior Office Helper'), ('OFFICE_HELPER', 'Office Helper'), ('HEAD_TECHNICAL_ASSISTANT', 'Head Technical Assistant'), ('ASSISTANT_STOREKEEPER', 'Assistant Storekeeper'), ('COMPUTER_OPERATOR', 'Computer Operator'), ('LIBRARIAN', 'Librarian'), ('LABORATORY_ASSISTANT', 'Laboratory Assistant'), ('ACCOUNT_OFFICER', 'Account Officer'), ('LIBRARY_INTERN', 'Library Intern'), ('SECURITY_GUARD', 'Security Guard'), ('SISTER', 'Sister')], max_length=100)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Designations',
                'ordering': ['rank'],
                'unique_together': {('designation', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='PlansPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Plans and Policy',
                'verbose_name_plural': 'Plans and Policies',
            },
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_programs', to='department.department')),
            ],
            options={
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('file', models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])])),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='department.programs')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('course_objective', ckeditor.fields.RichTextField()),
                ('topics_covered', ckeditor.fields.RichTextField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='department.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('roll', models.CharField(max_length=255)),
                ('photo', models.FileField(blank=True, null=True, upload_to='media/students/')),
                ('is_cr', models.BooleanField()),
                ('is_topper', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_department', to='department.department')),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('founded_at', models.DateField(blank=True, null=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_department', to='department.department')),
                ('social_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_social_media', to='home.socialmedia')),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('routine_png', models.ImageField(upload_to='media/routine/')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_semester', to='department.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('report', models.FileField(upload_to='media/files/project', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx'])])),
                ('published_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_projects', to='department.department')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('answer', ckeditor.fields.RichTextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_department', to='department.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='plans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_plans', to='department.planspolicy'),
        ),
        migrations.AddField(
            model_name='department',
            name='social_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_social_media', to='home.socialmedia'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('author', models.CharField(max_length=255)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_department', to='department.department')),
            ],
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, null=True)),
                ('responsibility', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_key_official', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='department.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_person', to='department.designation')),
                ('social_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socials', to='home.socialmedia')),
            ],
            options={
                'verbose_name_plural': 'Staff Members',
                'ordering': ['-designation_id'],
                'unique_together': {('name', 'designation')},
            },
        ),
    ]
