# Generated by Django 4.2.2 on 2023-06-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('DOECE', 'Department of Electronics and Communication Engineering'), ('DOCE', 'Department of Civil and Industrial Engineering'), ('DOAME', 'Department of AutoMobile and Mechanical Engineering'), ('DOARCH', 'Department of Architecture')], default='DOECE', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='designation',
            field=models.CharField(choices=[('CHIEF', 'Campus Chief'), ('ASSIST_CHIEF', 'Assistant Campus Chief'), ('HOD', 'Head of Department'), ('DHOD', 'Deputy Head of Department'), ('PROF', 'Professor'), ('ASSO_PROF', 'Associate Professor'), ('ASSIST_PROF', 'Assistant Professor'), ('LECT', 'Lecturer'), ('HELPING_STAFF', 'Helping Staff')], max_length=100),
        ),
    ]
