# Generated by Django 4.2.2 on 2023-06-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_name_alter_designation_designation'),
        ('department', '0002_alter_department_social_media'),
    ]

    operations = [
    ]
