# Generated by Django 4.2.2 on 2023-06-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_alter_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_academic',
            field=models.BooleanField(default=False),
        ),
    ]
