# Generated by Django 4.2.2 on 2023-06-29 09:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_department_is_academic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
        migrations.AlterField(
            model_name='planspolicy',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
