# Generated by Django 4.2.2 on 2023-06-29 09:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_alter_blog_department_alter_planspolicy_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='staffmember',
            name='started_at',
        ),
        migrations.AlterField(
            model_name='society',
            name='founded_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('routine_png', models.ImageField(upload_to='media/routine/')),
                ('programs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.programs')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.semester')),
            ],
        ),
    ]
