# Generated by Django 4.2.2 on 2023-06-29 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_remove_designation_ended_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='image',
        ),
    ]
