# Generated by Django 4.2.2 on 2023-06-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_remove_department_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('DOECE', 'Department of Electronics and Communication Engineering'), ('DOCE', 'Department of Civil and Industrial Engineering'), ('DOAME', 'Department of AutoMobile and Mechanical Engineering'), ('DOARCH', 'Department of Architecture'), ('Admninistartion', 'Administration'), ('Library', 'Library')], default='DOECE', max_length=100, unique=True),
        ),
    ]
