# Generated by Django 4.2.2 on 2023-06-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_alter_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='programs',
        ),
    ]
