# Generated by Django 4.2.2 on 2023-06-30 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0012_programs_slug_questionbank_slug_semester_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='plans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.planspolicy'),
        ),
    ]
