# Generated by Django 4.2.2 on 2023-06-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0013_alter_department_plans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_tooper',
            new_name='is_topper',
        ),
    ]
